In [7]:
import os
import sys
import platform

import torch

print("=" * 60)
print("ENVIRONNEMENT GOOGLE COLAB")
print("=" * 60)

print(f"Python            : {sys.version.split()[0]}")
print(f"Système           : {platform.system()}")
print(f"PyTorch           : {torch.__version__}")
print(f"CUDA disponible   : {torch.cuda.is_available()}")

if torch.cuda.is_available():
    print(f"GPU               : {torch.cuda.get_device_name(0)}")
else:
    print("GPU               : non détecté")
    print("Vérifie le type d'exécution de Google Colab.")

print("=" * 60)

============================================================
ENVIRONNEMENT GOOGLE COLAB
============================================================
Python            : 3.12.13
Système           : Linux
PyTorch           : 2.11.0+cpu
CUDA disponible   : False
GPU               : non détecté
Vérifie le type d'exécution de Google Colab.
============================================================

In [8]:
!pip install -q -U \
    sentence-transformers \
    langchain-text-splitters \
    langchain-experimental \
    faiss-cpu \
    pandas \
    numpy \
    matplotlib \
    tqdm \
    tiktoken

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 2.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.3/80.3 kB 6.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.4/57.4 kB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.2/211.2 kB 9.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 72.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 102.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 86.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 101.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 676.7/676.7 kB 38.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 58.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 41.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 5.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.5 which is incompatible.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.5.1 which is incompatible.

In [9]:
!pip install -q --force-reinstall \
    "numpy==2.0.2" \
    "pandas==2.2.2" \
    "requests==2.32.4"

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 1.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 491.3 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.2/19.2 MB 8.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 12.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.8/64.8 kB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.0/137.0 kB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.3/224.3 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 1.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.1/510.1 kB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 348.2/348.2 kB 7.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.1/131.1 kB 2.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
langchain-community 0.4.2 requires requests<3.0.0,>=2.32.5, but you have requests 2.32.4 which is incompatible.

In [10]:
import numpy as np
import pandas as pd
import requests
import torch

print("=" * 60)
print("VÉRIFICATION DES VERSIONS")
print("=" * 60)

print("NumPy   :", np.__version__)
print("Pandas  :", pd.__version__)
print("Requests:", requests.__version__)
print("PyTorch :", torch.__version__)
print("CUDA    :", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU     :", torch.cuda.get_device_name(0))

print("=" * 60)

============================================================
VÉRIFICATION DES VERSIONS
============================================================
NumPy   : 2.0.2
Pandas  : 2.2.2
Requests: 2.32.4
PyTorch : 2.11.0+cpu
CUDA    : False
============================================================

In [11]:
import faiss

from sentence_transformers import SentenceTransformer
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_experimental.text_splitter import SemanticChunker

print("FAISS : OK")
print("Sentence Transformers : OK")
print("RecursiveCharacterTextSplitter : OK")
print("SemanticChunker : OK")
print("\nEnvironnement prêt pour le benchmark du chunking.")

FAISS : OK
Sentence Transformers : OK
RecursiveCharacterTextSplitter : OK
SemanticChunker : OK

Environnement prêt pour le benchmark du chunking.

/tmp/ipykernel_4017/2175324990.py:5: DeprecationWarning: `langchain-experimental` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-experimental/issues/87 for details.
  from langchain_experimental.text_splitter import SemanticChunker

In [12]:
!pip install -q \
    sentence-transformers \
    langchain-text-splitters \
    langchain-experimental \
    faiss-cpu \
    tiktoken

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.

Décompression

In [13]:
!apt-get update -qq
!apt-get install -y -qq zip unzip

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)

In [14]:
original_zip = "/content/benchmark_dataset.zip"
repaired_zip = "/content/benchmark_dataset_repaired.zip"

In [19]:
!zip -FF "$original_zip" --out "$repaired_zip"

Fix archive (-FF) - salvage what can
 Found end record (EOCDR) - says expect single disk archive
Scanning for entries...
 copying: html\en-us-azure-architecture-777fa9b92470.html  (10326 bytes)
 copying: html\en-us-azure-architecture-patterns-2da035768373.html  (15553 bytes)
 copying: html\en-us_azure_architecture.html  (4511 bytes)
 copying: html\en-us_azure_architecture_ai-ml.html  (9555 bytes)
 copying: html\en-us_azure_architecture_browse.html  (300 bytes)
 copying: html\en-us_azure_architecture_data-guide.html  (7815 bytes)
 copying: html\en-us_azure_architecture_patterns.html  (7344 bytes)
 copying: markdown\well-architected__ai__design-principles.md  (7460 bytes)
 copying: markdown\well-architected__cost-optimization__cost-model.md  (7051 bytes)
 copying: markdown\well-architected__cost-optimization__design-patterns.md  (2677 bytes)
 copying: markdown\well-architected__cost-optimization__optimize-flow-costs.md  (5822 bytes)
 copying: markdown\well-architected__hpc__hpc-design-principles.md  (6251 bytes)
 copying: markdown\well-architected__microsoft-fabric__reliability.md  (5369 bytes)
 copying: markdown\well-architected__mission-critical__mission-critical-design-methodology.md  (2694 bytes)
 copying: markdown\well-architected__service-guides__azure-databricks.md  (25847 bytes)
 copying: markdown\well-architected__sustainability__overview.md  (4571 bytes)
 copying: markdown\well-architected__sustainability__sustainability-cost-optimization-recommendations.md  (5502 bytes)
 copying: pdf\azure_serverless_computing_cookbook.pdf  (20810810 bytes)
 copying: pdf\enterprise_cloud_strategy.pdf  (15098718 bytes)
Central Directory found...
EOCDR found ( 1 36041684)...

In [20]:
import zipfile
from pathlib import Path

repaired_zip = Path(
    "/content/benchmark_dataset_repaired.zip"
)

print("Archive créée :", repaired_zip.exists())
print(
    "Archive ZIP valide :",
    zipfile.is_zipfile(repaired_zip)
)

if repaired_zip.exists():
    print(
        "Taille :",
        repaired_zip.stat().st_size,
        "octets"
    )

Archive créée : True
Archive ZIP valide : True
Taille : 36041706 octets

In [21]:
import zipfile

valid_files = []
corrupted_files = []

with zipfile.ZipFile(
    repaired_zip,
    "r"
) as zip_ref:

    for member in zip_ref.infolist():
        try:
            zip_ref.read(member)
            valid_files.append(member.filename)

        except Exception as error:
            corrupted_files.append(
                (
                    member.filename,
                    str(error)
                )
            )

print("Fichiers lisibles :", len(valid_files))
print("Fichiers problématiques :", len(corrupted_files))

for filename, error in corrupted_files:
    print(filename, "->", error)

Fichiers lisibles : 19
Fichiers problématiques : 0

In [22]:
import zipfile
import shutil
from pathlib import Path

repaired_zip = Path(
    "/content/benchmark_dataset_repaired.zip"
)

extract_path = Path(
    "/content/benchmark_dataset"
)

if extract_path.exists():
    shutil.rmtree(extract_path)

extract_path.mkdir(
    parents=True,
    exist_ok=True
)

extracted = []
skipped = []

with zipfile.ZipFile(repaired_zip, "r") as zip_ref:

    for member in zip_ref.infolist():

        try:
            data = zip_ref.read(member)

            relative_path = (
                member.filename.replace("\\", "/")
            )

            destination = (
                extract_path / relative_path
            )

            destination.parent.mkdir(
                parents=True,
                exist_ok=True
            )

            destination.write_bytes(data)

            extracted.append(member.filename)

        except Exception as error:
            skipped.append(
                (member.filename, str(error))
            )

print("Fichiers extraits :", len(extracted))
print("Fichiers ignorés :", len(skipped))

for filename, error in skipped:
    print("-", filename, ":", error)

Fichiers extraits : 19
Fichiers ignorés : 0

In [23]:
all_files = [
    path
    for path in extract_path.rglob("*")
    if path.is_file()
]

print("Nombre de fichiers présents :", len(all_files))

for path in sorted(all_files):
    print(path.relative_to(extract_path))

Nombre de fichiers présents : 19
html/en-us-azure-architecture-777fa9b92470.html
html/en-us-azure-architecture-patterns-2da035768373.html
html/en-us_azure_architecture.html
html/en-us_azure_architecture_ai-ml.html
html/en-us_azure_architecture_browse.html
html/en-us_azure_architecture_data-guide.html
html/en-us_azure_architecture_patterns.html
markdown/well-architected__ai__design-principles.md
markdown/well-architected__cost-optimization__cost-model.md
markdown/well-architected__cost-optimization__design-patterns.md
markdown/well-architected__cost-optimization__optimize-flow-costs.md
markdown/well-architected__hpc__hpc-design-principles.md
markdown/well-architected__microsoft-fabric__reliability.md
markdown/well-architected__mission-critical__mission-critical-design-methodology.md
markdown/well-architected__service-guides__azure-databricks.md
markdown/well-architected__sustainability__overview.md
markdown/well-architected__sustainability__sustainability-cost-optimization-recommendations.md
pdf/azure_serverless_computing_cookbook.pdf
pdf/enterprise_cloud_strategy.pdf

In [24]:
from google.colab import files

uploaded = files.upload()

Saving azure_serverless_computing_cookbook.pdf to azure_serverless_computing_cookbook.pdf

In [26]:
import shutil
from pathlib import Path

uploaded_pdf = Path(
    "/content/azure_serverless_computing_cookbook.pdf"
)

destination_pdf = Path(
    "/content/benchmark_dataset/pdf/"
    "azure_serverless_computing_cookbook.pdf"
)

destination_pdf.parent.mkdir(
    parents=True,
    exist_ok=True
)

shutil.copy2(
    uploaded_pdf,
    destination_pdf
)

print(
    "PDF restauré :",
    destination_pdf.exists()
)

print(
    "Taille :",
    destination_pdf.stat().st_size,
    "octets"
)

PDF restauré : True
Taille : 23634988 octets

In [27]:
final_files = [
    path
    for path in extract_path.rglob("*")
    if path.is_file()
]

print(
    "Nombre final de fichiers :",
    len(final_files)
)

Nombre final de fichiers : 19

Cellule 2 : Vérifier que tout est bien extrait

In [29]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [30]:
import os

extract_path = "/content/benchmark_dataset"

for root, dirs, files in os.walk(extract_path):
    level = root.replace(extract_path, "").count(os.sep)
    indent = "    " * level
    print(f"{indent}{os.path.basename(root)}/")

    subindent = "    " * (level + 1)

    for f in files:
        print(f"{subindent}{f}")

benchmark_dataset/
    pdf/
        azure_serverless_computing_cookbook.pdf
        enterprise_cloud_strategy.pdf
    markdown/
        well-architected__mission-critical__mission-critical-design-methodology.md
        well-architected__cost-optimization__cost-model.md
        well-architected__ai__design-principles.md
        well-architected__cost-optimization__optimize-flow-costs.md
        well-architected__service-guides__azure-databricks.md
        well-architected__sustainability__sustainability-cost-optimization-recommendations.md
        well-architected__cost-optimization__design-patterns.md
        well-architected__microsoft-fabric__reliability.md
        well-architected__hpc__hpc-design-principles.md
        well-architected__sustainability__overview.md
    html/
        en-us_azure_architecture.html
        en-us-azure-architecture-patterns-2da035768373.html
        en-us_azure_architecture_patterns.html
        en-us-azure-architecture-777fa9b92470.html
        en-us_azure_architecture_data-guide.html
        en-us_azure_architecture_ai-ml.html
        en-us_azure_architecture_browse.html

Le notebook sera organisé  :

Import des bibliothèques

Chargement des documents

Parsing des Markdown, HTML et PDF

Nettoyage du texte

Implémentation des stratégies de chunking :

Fixed-size
Recursive
Semantic

Génération des embeddings (BGE)

Indexation FAISS

Recherche

Calcul des métriques (Recall@K, MRR, temps, nombre de chunks, etc.)

Comparaison des résultats dans des tableaux.

Cellule 1 — **Imports** **texte en gras**

In [31]:
!pip install -q pymupdf beautifulsoup4 markdown sentence-transformers faiss-cpu langchain langchain-experimental

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.7/25.7 MB 46.2 MB/s eta 0:00:00

In [32]:
import langchain
import langchain_core

print("LangChain :", langchain.__version__)
print("LangChain Core :", langchain_core.__version__)

LangChain : 1.3.13
LangChain Core : 1.4.9

In [33]:
from pathlib import Path
import os
import re
import time

from bs4 import BeautifulSoup
import markdown
import fitz

from langchain_core.documents import Document

print("Tous les imports sont OK ")

Tous les imports sont OK

In [34]:
from pathlib import Path

base = Path("/content/benchmark_dataset")

print("Le dossier existe :", base.exists())

print("\nContenu de benchmark_dataset :")

for item in base.iterdir():
    print(item, "->", "DOSSIER" if item.is_dir() else "FICHIER")

Le dossier existe : True

Contenu de benchmark_dataset :
/content/benchmark_dataset/pdf -> DOSSIER
/content/benchmark_dataset/markdown -> DOSSIER
/content/benchmark_dataset/html -> DOSSIER

In [35]:
from pathlib import Path

for f in Path("/content/benchmark_dataset").rglob("*"):
    print(f)

/content/benchmark_dataset/pdf
/content/benchmark_dataset/markdown
/content/benchmark_dataset/html
/content/benchmark_dataset/pdf/azure_serverless_computing_cookbook.pdf
/content/benchmark_dataset/pdf/enterprise_cloud_strategy.pdf
/content/benchmark_dataset/markdown/well-architected__mission-critical__mission-critical-design-methodology.md
/content/benchmark_dataset/markdown/well-architected__cost-optimization__cost-model.md
/content/benchmark_dataset/markdown/well-architected__ai__design-principles.md
/content/benchmark_dataset/markdown/well-architected__cost-optimization__optimize-flow-costs.md
/content/benchmark_dataset/markdown/well-architected__service-guides__azure-databricks.md
/content/benchmark_dataset/markdown/well-architected__sustainability__sustainability-cost-optimization-recommendations.md
/content/benchmark_dataset/markdown/well-architected__cost-optimization__design-patterns.md
/content/benchmark_dataset/markdown/well-architected__microsoft-fabric__reliability.md
/content/benchmark_dataset/markdown/well-architected__hpc__hpc-design-principles.md
/content/benchmark_dataset/markdown/well-architected__sustainability__overview.md
/content/benchmark_dataset/html/en-us_azure_architecture.html
/content/benchmark_dataset/html/en-us-azure-architecture-patterns-2da035768373.html
/content/benchmark_dataset/html/en-us_azure_architecture_patterns.html
/content/benchmark_dataset/html/en-us-azure-architecture-777fa9b92470.html
/content/benchmark_dataset/html/en-us_azure_architecture_data-guide.html
/content/benchmark_dataset/html/en-us_azure_architecture_ai-ml.html
/content/benchmark_dataset/html/en-us_azure_architecture_browse.html

In [36]:
from pathlib import Path

DATASET_PATH = Path("/content/benchmark_dataset")

markdown_files = list(DATASET_PATH.glob("markdown/*.md"))
html_files = list(DATASET_PATH.glob("html/*.html"))
pdf_files = list(DATASET_PATH.glob("pdf/*.pdf"))

print("Markdown :", len(markdown_files))
print("HTML :", len(html_files))
print("PDF :", len(pdf_files))

Markdown : 10
HTML : 7
PDF : 2

In [37]:
from pathlib import Path

for path in Path("/content").iterdir():
    print(path)

/content/.config
/content/azure_serverless_computing_cookbook.pdf
/content/benchmark_dataset.zip
/content/benchmark_dataset
/content/drive
/content/benchmark_dataset_repaired.zip
/content/sample_data

**1. Fonction de nettoyage**

In [38]:
import re

def clean_text(text: str) -> str:
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()

**2. Chargement des Markdown**

In [39]:
from bs4 import BeautifulSoup
import markdown
from langchain_core.documents import Document

documents = []

for file in markdown_files:
    with open(file, "r", encoding="utf-8") as f:
        raw_markdown = f.read()

    converted_html = markdown.markdown(
        raw_markdown,
        extensions=["fenced_code", "tables"]
    )

    text = BeautifulSoup(converted_html, "html.parser").get_text(
        separator="\n"
    )

    text = clean_text(text)

    documents.append(
        Document(
            page_content=text,
            metadata={
                "source": file.name,
                "format": "markdown"
            }
        )
    )

print("Markdown chargés :", len(documents))

Markdown chargés : 10

**3. Chargement des HTML**

In [40]:
for file in html_files:
    with open(file, "r", encoding="utf-8", errors="ignore") as f:
        raw_html = f.read()

    soup = BeautifulSoup(raw_html, "html.parser")

    for element in soup(["script", "style", "noscript", "svg"]):
        element.decompose()

    text = soup.get_text(separator="\n")
    text = clean_text(text)

    documents.append(
        Document(
            page_content=text,
            metadata={
                "source": file.name,
                "format": "html"
            }
        )
    )

print("Documents après HTML :", len(documents))

Documents après HTML : 17

**4. Chargement des PDF**

In [41]:
import fitz

for file in pdf_files:
    pdf = fitz.open(file)

    pages_text = []

    for page_number, page in enumerate(pdf):
        page_text = page.get_text("text")

        if page_text.strip():
            pages_text.append(page_text)

    pdf.close()

    text = "\n\n".join(pages_text)
    text = clean_text(text)

    documents.append(
        Document(
            page_content=text,
            metadata={
                "source": file.name,
                "format": "pdf"
            }
        )
    )

print("Total des documents :", len(documents))

Total des documents : 19

**Vérifier le contenu extrait**

In [42]:
for index, doc in enumerate(documents[:3], start=1):
    print("=" * 100)
    print("Document :", index)
    print("Métadonnées :", doc.metadata)
    print("Nombre de caractères :", len(doc.page_content))
    print()
    print(doc.page_content[:800])
    print()

====================================================================================================
Document : 1
Métadonnées : {'source': 'well-architected__mission-critical__mission-critical-design-methodology.md', 'format': 'markdown'}
Nombre de caractères : 5700

title: Design methodology for mission-critical workloads on Azure
description: Understand the architectural process of building a mature mission-critical application on Microsoft Azure.
author: calcof
ms.author: calcof
ms.date: 06/09/2025
ms.topic: concept-article

Design methodology for mission-critical workloads on Azure

Designing a mission-critical application on any cloud platform demands a thoughtful engineering approach. There's complexity related to: understanding the platform's capabilities, selecting the right services, configuring them correctly, operationalizing them effectively, and staying aligned with evolving best practices and service roadmaps.

To navigate this complexity, establish a clear and simple design methodology that aligns with your business requirements, particu

====================================================================================================
Document : 2
Métadonnées : {'source': 'well-architected__cost-optimization__cost-model.md', 'format': 'markdown'}
Nombre de caractères : 19970

title: Architecture strategies for creating a cost model
description: Learn how to create an estimate that focuses on predicting the combined costs of services and their associated expenses.
author: stephen-sumner
ms.author: ssumner
ms.date: 11/15/2023
ms.topic: concept-article

Architecture strategies for creating a cost model

Applies to this Azure Well-Architected Framework Cost Optimization checklist recommendation:

CO:02

Create and maintain a cost model. A cost model should estimate the initial cost, run rates, and ongoing costs. Negotiate a budget that covers a cost model and has a buffer for unplanned spending.

This guide describes the best practices for creating a cost model for your workload. A cost model is an estimate that predicts the combined costs of services and their ass

====================================================================================================
Document : 3
Métadonnées : {'source': 'well-architected__ai__design-principles.md', 'format': 'markdown'}
Nombre de caractères : 19631

title: Design Principles for AI Workloads on Azure
description: Review the design principles of the Azure Well-Architected Framework. Learn how to apply these principles to an AI workload.
author: PageWriter-MSFT
ms.author: prwilk
ms.date: 04/15/2024
ms.topic: concept-article
ms.update-cycle: 180-days

Design principles for AI workloads on Azure

This article outlines the core principles for AI workloads on Azure, with a focus on the AI aspects of an architecture. It's essential to consider all Azure Well-Architected Framework pillars collectively, including their trade-offs. Apply each pillar to the functional and nonfunctional requirements of the workload.

Reliability

When you run AI workloads on Azure, you need to consider many of the same reliability requirements that you consider f

**Étape 1 — Extraire le front matter Markdown**

In [43]:
import re
from typing import Tuple, Dict


def extract_front_matter(raw_text: str) -> Tuple[Dict[str, str], str]:
    """
    Sépare les métadonnées YAML placées au début d'un fichier Markdown
    du contenu documentaire réel.
    """

    metadata = {}

    # Cas standard : métadonnées entourées par ---
    yaml_match = re.match(
        r"^\s*---\s*\n(.*?)\n---\s*\n(.*)$",
        raw_text,
        flags=re.DOTALL
    )

    if yaml_match:
        yaml_block = yaml_match.group(1)
        content = yaml_match.group(2)

    else:
        # Cas des fichiers Microsoft sans séparateur ---
        lines = raw_text.splitlines()
        yaml_lines = []
        content_start = 0

        metadata_pattern = re.compile(
            r"^[A-Za-z0-9_.-]+\s*:"
        )

        for index, line in enumerate(lines):
            stripped = line.strip()

            if not stripped:
                if yaml_lines:
                    content_start = index + 1
                    break
                continue

            if metadata_pattern.match(stripped) or stripped.startswith("- "):
                yaml_lines.append(line)
            else:
                content_start = index
                break

        yaml_block = "\n".join(yaml_lines)
        content = "\n".join(lines[content_start:])

    # Extraction simple des champs clé: valeur
    for line in yaml_block.splitlines():
        match = re.match(r"^([A-Za-z0-9_.-]+)\s*:\s*(.*)$", line.strip())

        if match:
            key = match.group(1).strip()
            value = match.group(2).strip().strip("\"'")

            if value:
                metadata[key] = value

    return metadata, content

**Étape 2 — Recharger les documents Markdown proprement**

In [44]:
from bs4 import BeautifulSoup
from langchain_core.documents import Document
import markdown

documents = []

for file in markdown_files:

    with open(file, "r", encoding="utf-8", errors="ignore") as f:
        raw_markdown = f.read()

    front_matter, markdown_content = extract_front_matter(raw_markdown)

    converted_html = markdown.markdown(
        markdown_content,
        extensions=[
            "fenced_code",
            "tables"
        ]
    )

    text = BeautifulSoup(
        converted_html,
        "html.parser"
    ).get_text(separator="\n")

    text = clean_text(text)

    metadata = {
        "source": file.name,
        "format": "markdown",
        "title": front_matter.get("title", file.stem),
        "description": front_matter.get("description", ""),
        "document_date": front_matter.get("ms.date", ""),
        "topic": front_matter.get("ms.topic", "")
    }

    documents.append(
        Document(
            page_content=text,
            metadata=metadata
        )
    )

print("Markdown chargés :", len(documents))

Markdown chargés : 10

**Étape 3 — Recharger les HTML**

In [45]:
for file in html_files:

    with open(file, "r", encoding="utf-8", errors="ignore") as f:
        raw_html = f.read()

    soup = BeautifulSoup(raw_html, "html.parser")

    # Suppression des éléments inutiles pour la recherche
    for element in soup([
        "script",
        "style",
        "noscript",
        "svg",
        "form"
    ]):
        element.decompose()

    # Chercher le titre HTML
    title = ""

    if soup.title:
        title = soup.title.get_text(strip=True)

    text = soup.get_text(separator="\n")
    text = clean_text(text)

    documents.append(
        Document(
            page_content=text,
            metadata={
                "source": file.name,
                "format": "html",
                "title": title,
                "description": "",
                "document_date": "",
                "topic": ""
            }
        )
    )

print("Documents après HTML :", len(documents))

Documents après HTML : 17

**Étape 4 — Recharger les PDF page par page**

In [46]:
import fitz

for file in pdf_files:

    pdf = fitz.open(file)

    pdf_title = pdf.metadata.get("title", "") if pdf.metadata else ""

    for page_index, page in enumerate(pdf):

        page_text = page.get_text("text")
        page_text = clean_text(page_text)

        if not page_text:
            continue

        documents.append(
            Document(
                page_content=page_text,
                metadata={
                    "source": file.name,
                    "format": "pdf",
                    "title": pdf_title or file.stem,
                    "page": page_index + 1,
                    "description": "",
                    "document_date": "",
                    "topic": ""
                }
            )
        )

    pdf.close()

print("Nombre total d'unités documentaires :", len(documents))

Nombre total d'unités documentaires : 617

In [47]:
from collections import Counter

format_distribution = Counter(
    doc.metadata["format"]
    for doc in documents
)

empty_documents = [
    doc for doc in documents
    if not doc.page_content.strip()
]

document_lengths = [
    len(doc.page_content)
    for doc in documents
]

print("Répartition :", format_distribution)
print("Unités documentaires :", len(documents))
print("Documents vides :", len(empty_documents))
print("Longueur minimale :", min(document_lengths))
print("Longueur maximale :", max(document_lengths))
print(
    "Longueur moyenne :",
    round(sum(document_lengths) / len(document_lengths), 2)
)

Répartition : Counter({'pdf': 600, 'markdown': 10, 'html': 7})
Unités documentaires : 617
Documents vides : 0
Longueur minimale : 18
Longueur maximale : 81809
Longueur moyenne : 1723.93

**1. Installer le module de chunking**

In [48]:
!pip install -q langchain-text-splitters

In [49]:
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter

import time
import pandas as pd
import numpy as np

print("Imports de chunking OK ")

Imports de chunking OK

**2. Configuration expérimentale**

In [50]:
CHUNK_SIZES = [256, 512, 1024]
OVERLAP_RATIO = 0.20

print("Tailles testées :", CHUNK_SIZES)
print("Overlap :", int(OVERLAP_RATIO * 100), "%")

Tailles testées : [256, 512, 1024]
Overlap : 20 %

**3. Fonction pour créer les métadonnées des chunks**

In [51]:
def build_chunk(
    text: str,
    original_doc: Document,
    chunk_index: int,
    strategy: str,
    chunk_size: int,
    chunk_overlap: int
) -> Document:
    """
    Crée un chunk LangChain avec des métadonnées de traçabilité.
    """

    metadata = original_doc.metadata.copy()

    source_name = metadata.get("source", "unknown_source")
    page = metadata.get("page")

    if page is not None:
        chunk_id = (
            f"{strategy}__{chunk_size}__"
            f"{source_name}__page_{page}__chunk_{chunk_index}"
        )
    else:
        chunk_id = (
            f"{strategy}__{chunk_size}__"
            f"{source_name}__chunk_{chunk_index}"
        )

    metadata.update({
        "chunk_id": chunk_id,
        "chunk_index": chunk_index,
        "strategy": strategy,
        "configured_chunk_size": chunk_size,
        "configured_overlap": chunk_overlap,
        "actual_characters": len(text),
        "actual_words": len(text.split())
    })

    return Document(
        page_content=text,
        metadata=metadata
    )

**4. Implémenter le Fixed-size Chunking**

In [52]:
def fixed_size_chunking(
    documents: list[Document],
    chunk_size: int,
    chunk_overlap: int
) -> list[Document]:
    """
    Découpe chaque document avec une fenêtre fixe de caractères.
    """

    if chunk_size <= 0:
        raise ValueError("chunk_size doit être supérieur à 0.")

    if chunk_overlap < 0:
        raise ValueError("chunk_overlap ne peut pas être négatif.")

    if chunk_overlap >= chunk_size:
        raise ValueError(
            "chunk_overlap doit être strictement inférieur à chunk_size."
        )

    step = chunk_size - chunk_overlap
    chunks = []

    for doc in documents:
        text = doc.page_content.strip()

        if not text:
            continue

        chunk_index = 0

        for start in range(0, len(text), step):
            end = start + chunk_size
            chunk_text = text[start:end].strip()

            if not chunk_text:
                continue

            chunks.append(
                build_chunk(
                    text=chunk_text,
                    original_doc=doc,
                    chunk_index=chunk_index,
                    strategy="fixed",
                    chunk_size=chunk_size,
                    chunk_overlap=chunk_overlap
                )
            )

            chunk_index += 1

            if end >= len(text):
                break

    return chunks

**5. Implémenter le Recursive Chunking**

In [53]:
def recursive_chunking(
    documents: list[Document],
    chunk_size: int,
    chunk_overlap: int
) -> list[Document]:
    """
    Découpe les documents en privilégiant les frontières naturelles.
    """

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        separators=[
            "\n\n",
            "\n",
            ". ",
            "? ",
            "! ",
            "; ",
            ", ",
            " ",
            ""
        ],
        length_function=len,
        keep_separator=True,
        is_separator_regex=False
    )

    chunks = []

    for doc in documents:
        text = doc.page_content.strip()

        if not text:
            continue

        split_texts = splitter.split_text(text)

        for chunk_index, chunk_text in enumerate(split_texts):
            chunk_text = chunk_text.strip()

            if not chunk_text:
                continue

            chunks.append(
                build_chunk(
                    text=chunk_text,
                    original_doc=doc,
                    chunk_index=chunk_index,
                    strategy="recursive",
                    chunk_size=chunk_size,
                    chunk_overlap=chunk_overlap
                )
            )

    return chunks

**6. Exécuter les expériences Fixed et Recursive**

In [55]:
chunking_results = {}
execution_records = []

for chunk_size in CHUNK_SIZES:
    chunk_overlap = int(chunk_size * OVERLAP_RATIO)

    # Fixed-size
    start_time = time.perf_counter()

    fixed_chunks = fixed_size_chunking(
        documents=documents,
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap
    )

    fixed_time = time.perf_counter() - start_time

    chunking_results[("fixed", chunk_size)] = fixed_chunks

    execution_records.append({
        "strategy": "fixed",
        "chunk_size": chunk_size,
        "chunk_overlap": chunk_overlap,
        "number_of_chunks": len(fixed_chunks),
        "chunking_time_seconds": fixed_time
    })

    # Recursive
    start_time = time.perf_counter()

    recursive_chunks = recursive_chunking(
        documents=documents,
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap
    )

    recursive_time = time.perf_counter() - start_time

    chunking_results[("recursive", chunk_size)] = recursive_chunks

    execution_records.append({
        "strategy": "recursive",
        "chunk_size": chunk_size,
        "chunk_overlap": chunk_overlap,
        "number_of_chunks": len(recursive_chunks),
        "chunking_time_seconds": recursive_time
    })

print("Expériences Fixed et Recursive terminées ")

Expériences Fixed et Recursive terminées

**7. Vérifier les résultats**

In [56]:
execution_df = pd.DataFrame(execution_records)

execution_df

,strategy,chunk_size,chunk_overlap,number_of_chunks,chunking_time_seconds
0,fixed,256,51,5343,0.238641
1,recursive,256,51,5727,0.346087
2,fixed,512,102,2751,0.095606
3,recursive,512,102,2870,0.279258
4,fixed,1024,204,1478,0.180456
5,recursive,1024,204,1483,0.382008

**8. Calculer les statistiques détaillées**

In [57]:
def calculate_chunk_statistics(
    chunks: list[Document],
    strategy: str,
    chunk_size: int
) -> dict:
    """
    Calcule les statistiques descriptives d'une collection de chunks.
    """

    character_lengths = np.array([
        len(chunk.page_content)
        for chunk in chunks
    ])

    word_lengths = np.array([
        len(chunk.page_content.split())
        for chunk in chunks
    ])

    return {
        "strategy": strategy,
        "chunk_size": chunk_size,
        "number_of_chunks": len(chunks),

        "mean_characters": round(character_lengths.mean(), 2),
        "median_characters": round(float(np.median(character_lengths)), 2),
        "min_characters": int(character_lengths.min()),
        "max_characters": int(character_lengths.max()),
        "std_characters": round(character_lengths.std(), 2),

        "mean_words": round(word_lengths.mean(), 2),
        "median_words": round(float(np.median(word_lengths)), 2),
        "min_words": int(word_lengths.min()),
        "max_words": int(word_lengths.max())
    }

In [58]:
statistics_records = []

for (strategy, chunk_size), chunks in chunking_results.items():
    statistics_records.append(
        calculate_chunk_statistics(
            chunks=chunks,
            strategy=strategy,
            chunk_size=chunk_size
        )
    )

statistics_df = pd.DataFrame(statistics_records)

statistics_df = statistics_df.sort_values(
    by=["chunk_size", "strategy"]
).reset_index(drop=True)

statistics_df

,strategy,chunk_size,number_of_chunks,mean_characters,median_characters,min_characters,max_characters,std_characters,mean_words,median_words,min_words,max_words
0,fixed,256,5343,243.78,256.0,18,256,38.68,34.78,38.0,2,53
1,recursive,256,5727,190.11,202.0,1,256,54.07,26.88,29.0,1,51
2,fixed,512,2751,465.42,512.0,18,512,102.96,65.57,73.0,2,98
3,recursive,512,2870,408.76,451.0,12,512,107.13,57.70,64.0,1,95
4,fixed,1024,1478,838.22,1023.0,18,1024,264.33,117.32,134.0,3,188
5,recursive,1024,1483,792.34,915.0,18,1024,242.52,110.88,119.0,3,187

**9. Ajouter le temps d’exécution au tableau final**

In [59]:
benchmark_chunking_df = statistics_df.merge(
    execution_df[
        [
            "strategy",
            "chunk_size",
            "chunk_overlap",
            "chunking_time_seconds"
        ]
    ],
    on=["strategy", "chunk_size"],
    how="left"
)

benchmark_chunking_df[
    "chunking_time_seconds"
] = benchmark_chunking_df[
    "chunking_time_seconds"
].round(4)

benchmark_chunking_df

,strategy,chunk_size,number_of_chunks,mean_characters,median_characters,min_characters,max_characters,std_characters,mean_words,median_words,min_words,max_words,chunk_overlap,chunking_time_seconds
0,fixed,256,5343,243.78,256.0,18,256,38.68,34.78,38.0,2,53,51,0.2386
1,recursive,256,5727,190.11,202.0,1,256,54.07,26.88,29.0,1,51,51,0.3461
2,fixed,512,2751,465.42,512.0,18,512,102.96,65.57,73.0,2,98,102,0.0956
3,recursive,512,2870,408.76,451.0,12,512,107.13,57.70,64.0,1,95,102,0.2793
4,fixed,1024,1478,838.22,1023.0,18,1024,264.33,117.32,134.0,3,188,204,0.1805
5,recursive,1024,1483,792.34,915.0,18,1024,242.52,110.88,119.0,3,187,204,0.3820

**10. Vérifier visuellement quelques chunks**

In [60]:
def display_chunk_samples(
    strategy: str,
    chunk_size: int,
    number_of_samples: int = 3
) -> None:

    chunks = chunking_results[(strategy, chunk_size)]

    print(
        f"Stratégie : {strategy} | "
        f"Chunk size : {chunk_size} | "
        f"Nombre total : {len(chunks)}"
    )

    for chunk in chunks[:number_of_samples]:
        print("\n" + "=" * 100)
        print("Chunk ID :", chunk.metadata["chunk_id"])
        print("Source :", chunk.metadata["source"])
        print(
            "Taille réelle :",
            chunk.metadata["actual_characters"],
            "caractères"
        )
        print("-" * 100)
        print(chunk.page_content)

In [61]:
#fixzd
display_chunk_samples(
    strategy="fixed",
    chunk_size=512,
    number_of_samples=3
)

Stratégie : fixed | Chunk size : 512 | Nombre total : 2751

====================================================================================================
Chunk ID : fixed__512__well-architected__mission-critical__mission-critical-design-methodology.md__chunk_0
Source : well-architected__mission-critical__mission-critical-design-methodology.md
Taille réelle : 512 caractères
----------------------------------------------------------------------------------------------------
Design methodology for mission-critical workloads on Azure

Designing a mission-critical application on any cloud platform demands a thoughtful engineering approach. There's complexity related to: understanding the platform's capabilities, selecting the right services, configuring them correctly, operationalizing them effectively, and staying aligned with evolving best practices and service roadmaps.

To navigate this complexity, establish a clear and simple design methodology that aligns with your business

====================================================================================================
Chunk ID : fixed__512__well-architected__mission-critical__mission-critical-design-methodology.md__chunk_1
Source : well-architected__mission-critical__mission-critical-design-methodology.md
Taille réelle : 512 caractères
----------------------------------------------------------------------------------------------------
vigate this complexity, establish a clear and simple design methodology that aligns with your business requirements, particularly around uptime and recovery. When decision-making becomes challenging or you find yourself stuck in analysis paralysis, return to your methodology as a reference point. It can help validate your choices, keep your design focused, and ensure alignment with your overall goals.

This article suggests a design methodology that's informed by insights gained from reviewing numerous miss

====================================================================================================
Chunk ID : fixed__512__well-architected__mission-critical__mission-critical-design-methodology.md__chunk_2
Source : well-architected__mission-critical__mission-critical-design-methodology.md
Taille réelle : 511 caractères
----------------------------------------------------------------------------------------------------
article suggests a design methodology that's informed by insights gained from reviewing numerous mission-critical applications deployed on Azure.

Design for your reliability objectives

Mission critical doesn't mean the same for everyone. The architecture will vary by the workload's business requirements and acceptable downtime. Those are often defined by Service Level Objectives (SLOs), such as 99.9% vs. 99.999% availability. Consider availability objectives to be more than just uptime. They represent co

In [62]:
#recursive
display_chunk_samples(
    strategy="recursive",
    chunk_size=512,
    number_of_samples=3
)

Stratégie : recursive | Chunk size : 512 | Nombre total : 2870

====================================================================================================
Chunk ID : recursive__512__well-architected__mission-critical__mission-critical-design-methodology.md__chunk_0
Source : well-architected__mission-critical__mission-critical-design-methodology.md
Taille réelle : 403 caractères
----------------------------------------------------------------------------------------------------
Design methodology for mission-critical workloads on Azure

Designing a mission-critical application on any cloud platform demands a thoughtful engineering approach. There's complexity related to: understanding the platform's capabilities, selecting the right services, configuring them correctly, operationalizing them effectively, and staying aligned with evolving best practices and service roadmaps.

====================================================================================================
Chunk ID : recursive__512__well-architected__mission-critical__mission-critical-design-methodology.md__chunk_1
Source : well-architected__mission-critical__mission-critical-design-methodology.md
Taille réelle : 409 caractères
----------------------------------------------------------------------------------------------------
To navigate this complexity, establish a clear and simple design methodology that aligns with your business requirements, particularly around uptime and recovery. When decision-making becomes challenging or you find yourself stuck in analysis paralysis, return to your methodology as a reference point. It can help validate your choices, keep your design focused, and ensure alignment with your overall goals.

====================================================================================================
Chunk ID : recursive__512__well-architected__mission-critical__mission-critical-design-methodology.md__chunk_2
Source : well-architected__mission-critical__mission-critical-design-methodology.md
Taille réelle : 190 caractères
----------------------------------------------------------------------------------------------------
This article suggests a design methodology that's informed by insights gained from reviewing numerous mission-critical applications deployed on Azure.

Design for your reliability objectives

In [63]:
#verefication automatique
def validate_chunks(
    chunks: list[Document],
    expected_strategy: str,
    expected_chunk_size: int
) -> dict:

    empty_chunks = [
        chunk for chunk in chunks
        if not chunk.page_content.strip()
    ]

    duplicated_ids = (
        len({
            chunk.metadata["chunk_id"]
            for chunk in chunks
        }) != len(chunks)
    )

    oversized_chunks = [
        chunk for chunk in chunks
        if len(chunk.page_content) > expected_chunk_size
    ]

    incorrect_strategies = [
        chunk for chunk in chunks
        if chunk.metadata["strategy"] != expected_strategy
    ]

    return {
        "strategy": expected_strategy,
        "chunk_size": expected_chunk_size,
        "total_chunks": len(chunks),
        "empty_chunks": len(empty_chunks),
        "duplicated_chunk_ids": duplicated_ids,
        "oversized_chunks": len(oversized_chunks),
        "incorrect_strategy_metadata": len(incorrect_strategies)
    }

In [64]:
validation_records = []

for (strategy, chunk_size), chunks in chunking_results.items():
    validation_records.append(
        validate_chunks(
            chunks=chunks,
            expected_strategy=strategy,
            expected_chunk_size=chunk_size
        )
    )

validation_df = pd.DataFrame(validation_records)

validation_df

,strategy,chunk_size,total_chunks,empty_chunks,duplicated_chunk_ids,oversized_chunks,incorrect_strategy_metadata
0,fixed,256,5343,0,False,0,0
1,recursive,256,5727,0,False,0,0
2,fixed,512,2751,0,False,0,0
3,recursive,512,2870,0,False,0,0
4,fixed,1024,1478,0,False,0,0
5,recursive,1024,1483,0,False,0,0

**12. Sauvegarder les premiers résultats**

---

In [65]:


OUTPUT_DIR = Path("/content/chunking_benchmark_results")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

benchmark_chunking_df.to_csv(
    OUTPUT_DIR / "fixed_recursive_statistics.csv",
    index=False
)

validation_df.to_csv(
    OUTPUT_DIR / "fixed_recursive_validation.csv",
    index=False
)

print("Résultats sauvegardés dans :", OUTPUT_DIR)

Résultats sauvegardés dans : /content/chunking_benchmark_results

# **le Semantic Chunking**

> Ajouter une citation

In [66]:
!pip install -q \
    langchain-experimental \
    langchain-huggingface \
    sentence-transformers

In [67]:
from langchain_experimental.text_splitter import SemanticChunker
from langchain_huggingface import HuggingFaceEmbeddings

print("Imports Semantic Chunking OK ")

Imports Semantic Chunking OK

**Charger le modèle d’embedding BGE**

In [68]:
import torch

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

print("Device détecté :", DEVICE)
EMBEDDING_MODEL_NAME = "BAAI/bge-small-en-v1.5"

embedding_model = HuggingFaceEmbeddings(
    model_name=EMBEDDING_MODEL_NAME,
    model_kwargs={
        "device": DEVICE
    },
    encode_kwargs={
        "normalize_embeddings": True,
        "batch_size": 32
    }
)

print("Modèle chargé :", EMBEDDING_MODEL_NAME)
print("Normalisation des embeddings : oui")
print("Batch size : 32")
print("Device :", DEVICE)

Device détecté : cpu

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/94.8k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/743 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  133MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Modèle chargé : BAAI/bge-small-en-v1.5
Normalisation des embeddings : oui
Batch size : 32
Device : cpu

**Vérifier la dimension des embeddings**

In [69]:
test_vector = embedding_model.embed_query(
    "Azure workloads should be reliable and cost efficient."
)

EMBEDDING_DIMENSION = len(test_vector)

print("Dimension de l'embedding :", EMBEDDING_DIMENSION)
print("Premières valeurs :", test_vector[:5])

Dimension de l'embedding : 384
Premières valeurs : [-0.07215326279401779, -0.03775668516755104, -0.00829135812819004, -0.026757605373859406, 0.03381075710058212]

**Configuration du benchmark sémantique**

In [70]:
SEMANTIC_PERCENTILES = [85, 90, 95]

print("Seuils sémantiques testés :", SEMANTIC_PERCENTILES)

Seuils sémantiques testés : [85, 90, 95]

**Fonction de Semantic Chunking**

In [71]:
def semantic_chunking(
    documents: list[Document],
    embeddings,
    breakpoint_threshold_amount: float
) -> list[Document]:
    """
    Découpe les documents selon les changements sémantiques
    entre groupes de phrases.
    """

    splitter = SemanticChunker(
        embeddings=embeddings,
        breakpoint_threshold_type="percentile",
        breakpoint_threshold_amount=breakpoint_threshold_amount,
        sentence_split_regex=r"(?<=[.?!])\s+"
    )

    semantic_chunks = []

    for doc in documents:
        text = doc.page_content.strip()

        if not text:
            continue

        try:
            split_documents = splitter.create_documents(
                texts=[text],
                metadatas=[doc.metadata.copy()]
            )

        except Exception as error:
            print(
                "Erreur pour le document :",
                doc.metadata.get("source")
            )
            print(type(error).__name__, ":", error)
            continue

        for chunk_index, split_doc in enumerate(split_documents):
            chunk_text = split_doc.page_content.strip()

            if not chunk_text:
                continue

            metadata = split_doc.metadata.copy()

            source_name = metadata.get(
                "source",
                "unknown_source"
            )

            page = metadata.get("page")

            if page is not None:
                chunk_id = (
                    f"semantic__p{breakpoint_threshold_amount}__"
                    f"{source_name}__page_{page}__"
                    f"chunk_{chunk_index}"
                )
            else:
                chunk_id = (
                    f"semantic__p{breakpoint_threshold_amount}__"
                    f"{source_name}__chunk_{chunk_index}"
                )

            metadata.update({
                "chunk_id": chunk_id,
                "chunk_index": chunk_index,
                "strategy": "semantic",
                "semantic_threshold_type": "percentile",
                "semantic_threshold_amount":
                    breakpoint_threshold_amount,
                "configured_chunk_size": None,
                "configured_overlap": 0,
                "actual_characters": len(chunk_text),
                "actual_words": len(chunk_text.split())
            })

            semantic_chunks.append(
                Document(
                    page_content=chunk_text,
                    metadata=metadata
                )
            )

    return semantic_chunks

In [72]:
test_documents = [documents[0]]

start_time = time.perf_counter()

test_semantic_chunks = semantic_chunking(
    documents=test_documents,
    embeddings=embedding_model,
    breakpoint_threshold_amount=90
)

test_duration = time.perf_counter() - start_time

print("Chunks créés :", len(test_semantic_chunks))
print("Temps :", round(test_duration, 3), "secondes")

Chunks créés : 6
Temps : 10.583 secondes

In [73]:
for chunk in test_semantic_chunks[:3]:
    print("\n" + "=" * 100)
    print("Chunk ID :", chunk.metadata["chunk_id"])
    print("Caractères :", len(chunk.page_content))
    print("Mots :", len(chunk.page_content.split()))
    print("-" * 100)
    print(chunk.page_content[:1000])

====================================================================================================
Chunk ID : semantic__p90__well-architected__mission-critical__mission-critical-design-methodology.md__chunk_0
Caractères : 403
Mots : 48
----------------------------------------------------------------------------------------------------
Design methodology for mission-critical workloads on Azure

Designing a mission-critical application on any cloud platform demands a thoughtful engineering approach. There's complexity related to: understanding the platform's capabilities, selecting the right services, configuring them correctly, operationalizing them effectively, and staying aligned with evolving best practices and service roadmaps.

====================================================================================================
Chunk ID : semantic__p90__well-architected__mission-critical__mission-critical-design-methodology.md__chunk_1
Caractères : 1255
Mots : 177
----------------------------------------------------------------------------------------------------
To navigate this complexity, establish a clear and simple design methodology that aligns with your business requirements, particularly around uptime and recovery. When decision-making becomes challenging or you find yourself stuck in analysis paralysis, return to your methodology as a reference point. It can help validate your choices, keep your design focused, and ensure alignment with your overall goals. This article suggests a design methodology that's informed by insights gained from reviewing numerous mission-critical applications deployed on Azure. Design for your reliability objectives

Mission critical doesn't mean the same for everyone. The architecture will vary by the workload's business requirements and acceptable downtime. Those are often defined by Service Level Objectives (SLOs), such as 99.9% vs. 99.999% availability. Consider availability objectives to be more than just uptime. They represent consistent service relative to a healthy application state. As a starting poi

====================================================================================================
Chunk ID : semantic__p90__well-architected__mission-critical__mission-critical-design-methodology.md__chunk_2
Caractères : 1592
Mots : 208
----------------------------------------------------------------------------------------------------
As a draft target architecture takes shape and cost and complexity become clearer, the initial requirements may be revisited, challenged, adjusted, or addressed through alternative solutions. For example, while a single-region, multi-zone setup may suffice for many critical workloads, higher reliability demands more engineering effort and complexity. Avoid defaulting to complex solutions like active-active multi-region unless there are strong requirements to do so. RTO (Recovery Time Objective) and RPO (Recovery Point Objective) are also key in defining reliability needs. For example, if your goal is to recover an application in under a minute, backup-based or active-passive strategies likely won't be fast enough. Refer to
Recommendations for defining reliability targets

Strive for end-to-end automation

Adopt a comprehensive automation strategy that spans both deployment and ongoing management activities. This methodology emphasizes consistency, repeatability, and resilience through

**Exécuter le Semantic Chunking sur tout le corpus**

In [74]:
semantic_execution_records = []

for percentile in SEMANTIC_PERCENTILES:

    print(
        f"\nLancement du Semantic Chunking "
        f"avec percentile={percentile}..."
    )

    start_time = time.perf_counter()

    semantic_chunks = semantic_chunking(
        documents=documents,
        embeddings=embedding_model,
        breakpoint_threshold_amount=percentile
    )

    elapsed_time = time.perf_counter() - start_time

    chunking_results[
        ("semantic", percentile)
    ] = semantic_chunks

    semantic_execution_records.append({
        "strategy": "semantic",
        "semantic_percentile": percentile,
        "number_of_chunks": len(semantic_chunks),
        "chunking_time_seconds": elapsed_time
    })

    print("Chunks :", len(semantic_chunks))
    print("Temps :", round(elapsed_time, 2), "secondes")

print("\nExpériences Semantic Chunking terminées ✅")

Lancement du Semantic Chunking avec percentile=85...
Chunks : 1917
Temps : 1278.76 secondes

Lancement du Semantic Chunking avec percentile=90...
Chunks : 1585
Temps : 1274.51 secondes

Lancement du Semantic Chunking avec percentile=95...
Chunks : 1309
Temps : 1281.1 secondes

Expériences Semantic Chunking terminées ✅

**Afficher les temps du Semantic Chunkinga**

In [75]:
semantic_execution_df = pd.DataFrame(
    semantic_execution_records
)

semantic_execution_df[
    "chunking_time_seconds"
] = semantic_execution_df[
    "chunking_time_seconds"
].round(4)

semantic_execution_df

   strategy  semantic_percentile  number_of_chunks  chunking_time_seconds
0  semantic                   85              1917              1278.7568
1  semantic                   90              1585              1274.5139
2  semantic                   95              1309              1281.0977

**Calculer les statistiques des chunks sémantiques**

In [76]:
def calculate_semantic_statistics(
    chunks: list[Document],
    percentile: int
) -> dict:

    character_lengths = np.array([
        len(chunk.page_content)
        for chunk in chunks
    ])

    word_lengths = np.array([
        len(chunk.page_content.split())
        for chunk in chunks
    ])

    return {
        "strategy": "semantic",
        "configuration": f"percentile_{percentile}",
        "semantic_percentile": percentile,
        "number_of_chunks": len(chunks),

        "mean_characters":
            round(float(character_lengths.mean()), 2),

        "median_characters":
            round(float(np.median(character_lengths)), 2),

        "min_characters":
            int(character_lengths.min()),

        "max_characters":
            int(character_lengths.max()),

        "std_characters":
            round(float(character_lengths.std()), 2),

        "mean_words":
            round(float(word_lengths.mean()), 2),

        "median_words":
            round(float(np.median(word_lengths)), 2),

        "min_words":
            int(word_lengths.min()),

        "max_words":
            int(word_lengths.max())
    }

In [77]:
semantic_statistics_records = []

for percentile in SEMANTIC_PERCENTILES:
    chunks = chunking_results[
        ("semantic", percentile)
    ]

    semantic_statistics_records.append(
        calculate_semantic_statistics(
            chunks=chunks,
            percentile=percentile
        )
    )

semantic_statistics_df = pd.DataFrame(
    semantic_statistics_records
)

semantic_statistics_df

,strategy,configuration,semantic_percentile,number_of_chunks,mean_characters,median_characters,min_characters,max_characters,std_characters,mean_words,median_words,min_words,max_words
0,semantic,percentile_85,85,1917,552.79,419.0,1,4033,494.65,77.74,60.0,1,552
1,semantic,percentile_90,90,1585,668.79,481.0,1,6983,645.49,94.02,69.0,1,997
2,semantic,percentile_95,95,1309,810.01,534.0,5,8391,950.66,113.85,78.0,1,1186

**le temps d’exécution**

In [78]:
semantic_benchmark_df = semantic_statistics_df.merge(
    semantic_execution_df[
        [
            "semantic_percentile",
            "chunking_time_seconds"
        ]
    ],
    on="semantic_percentile",
    how="left"
)

semantic_benchmark_df

,strategy,configuration,semantic_percentile,number_of_chunks,mean_characters,median_characters,min_characters,max_characters,std_characters,mean_words,median_words,min_words,max_words,chunking_time_seconds
0,semantic,percentile_85,85,1917,552.79,419.0,1,4033,494.65,77.74,60.0,1,552,1278.7568
1,semantic,percentile_90,90,1585,668.79,481.0,1,6983,645.49,94.02,69.0,1,997,1274.5139
2,semantic,percentile_95,95,1309,810.01,534.0,5,8391,950.66,113.85,78.0,1,1186,1281.0977

**Valider les chunks sémantiques**

In [79]:
def validate_semantic_chunks(
    chunks: list[Document],
    percentile: int
) -> dict:

    empty_chunks = [
        chunk
        for chunk in chunks
        if not chunk.page_content.strip()
    ]

    chunk_ids = [
        chunk.metadata["chunk_id"]
        for chunk in chunks
    ]

    duplicated_ids = (
        len(chunk_ids) != len(set(chunk_ids))
    )

    incorrect_strategy = [
        chunk
        for chunk in chunks
        if chunk.metadata.get("strategy") != "semantic"
    ]

    very_small_chunks = [
        chunk
        for chunk in chunks
        if len(chunk.page_content) < 50
    ]

    return {
        "strategy": "semantic",
        "semantic_percentile": percentile,
        "total_chunks": len(chunks),
        "empty_chunks": len(empty_chunks),
        "duplicated_chunk_ids": duplicated_ids,
        "incorrect_strategy_metadata":
            len(incorrect_strategy),
        "chunks_under_50_characters":
            len(very_small_chunks)
    }

In [80]:
semantic_validation_records = []

for percentile in SEMANTIC_PERCENTILES:
    chunks = chunking_results[
        ("semantic", percentile)
    ]

    semantic_validation_records.append(
        validate_semantic_chunks(
            chunks=chunks,
            percentile=percentile
        )
    )

semantic_validation_df = pd.DataFrame(
    semantic_validation_records
)

semantic_validation_df

,strategy,semantic_percentile,total_chunks,empty_chunks,duplicated_chunk_ids,incorrect_strategy_metadata,chunks_under_50_characters
0,semantic,85,1917,0,False,0,82
1,semantic,90,1585,0,False,0,51
2,semantic,95,1309,0,False,0,26

**Comparaison visuelle des trois seuils**

In [81]:
def display_semantic_samples(
    percentile: int,
    number_of_samples: int = 3
) -> None:

    chunks = chunking_results[
        ("semantic", percentile)
    ]

    print(
        "Stratégie : semantic | "
        f"Percentile : {percentile} | "
        f"Nombre total : {len(chunks)}"
    )

    for chunk in chunks[:number_of_samples]:
        print("\n" + "=" * 100)
        print("Chunk ID :", chunk.metadata["chunk_id"])
        print(
            "Taille réelle :",
            chunk.metadata["actual_characters"],
            "caractères"
        )
        print("-" * 100)
        print(chunk.page_content[:1500])

In [82]:
display_semantic_samples(
    percentile=85,
    number_of_samples=3
)

Stratégie : semantic | Percentile : 85 | Nombre total : 1917

====================================================================================================
Chunk ID : semantic__p85__well-architected__mission-critical__mission-critical-design-methodology.md__chunk_0
Taille réelle : 403 caractères
----------------------------------------------------------------------------------------------------
Design methodology for mission-critical workloads on Azure

Designing a mission-critical application on any cloud platform demands a thoughtful engineering approach. There's complexity related to: understanding the platform's capabilities, selecting the right services, configuring them correctly, operationalizing them effectively, and staying aligned with evolving best practices and service roadmaps.

====================================================================================================
Chunk ID : semantic__p85__well-architected__mission-critical__mission-critical-design-methodology.md__chunk_1
Taille réelle : 1255 caractères
----------------------------------------------------------------------------------------------------
To navigate this complexity, establish a clear and simple design methodology that aligns with your business requirements, particularly around uptime and recovery. When decision-making becomes challenging or you find yourself stuck in analysis paralysis, return to your methodology as a reference point. It can help validate your choices, keep your design focused, and ensure alignment with your overall goals. This article suggests a design methodology that's informed by insights gained from reviewing numerous mission-critical applications deployed on Azure. Design for your reliability objectives

Mission critical doesn't mean the same for everyone. The architecture will vary by the workload's business requirements and acceptable downtime. Those are often defined by Service Level Objectives (SLOs), such as 99.9% vs. 99.999% availability. Consider availability objectives to be more than just uptime. They represent consistent service relative to a healthy application state. As a starting point, teams should define how much downtime is acceptable. Use an Uptime/Downtime calculator to determine the tolerable downtime. This design methodology can serve as a starting point for architectural decisions and tradeoffs after objectives have been set.

====================================================================================================
Chunk ID : semantic__p85__well-architected__mission-critical__mission-critical-design-methodology.md__chunk_2
Taille réelle : 352 caractères
----------------------------------------------------------------------------------------------------
As a draft target architecture takes shape and cost and complexity become clearer, the initial requirements may be revisited, challenged, adjusted, or addressed through alternative solutions. For example, while a single-region, multi-zone setup may suffice for many critical workloads, higher reliability demands more engineering effort and complexity.

In [83]:
display_semantic_samples(
    percentile=90,
    number_of_samples=3
)

Stratégie : semantic | Percentile : 90 | Nombre total : 1585

====================================================================================================
Chunk ID : semantic__p90__well-architected__mission-critical__mission-critical-design-methodology.md__chunk_0
Taille réelle : 403 caractères
----------------------------------------------------------------------------------------------------
Design methodology for mission-critical workloads on Azure

Designing a mission-critical application on any cloud platform demands a thoughtful engineering approach. There's complexity related to: understanding the platform's capabilities, selecting the right services, configuring them correctly, operationalizing them effectively, and staying aligned with evolving best practices and service roadmaps.

====================================================================================================
Chunk ID : semantic__p90__well-architected__mission-critical__mission-critical-design-methodology.md__chunk_1
Taille réelle : 1255 caractères
----------------------------------------------------------------------------------------------------
To navigate this complexity, establish a clear and simple design methodology that aligns with your business requirements, particularly around uptime and recovery. When decision-making becomes challenging or you find yourself stuck in analysis paralysis, return to your methodology as a reference point. It can help validate your choices, keep your design focused, and ensure alignment with your overall goals. This article suggests a design methodology that's informed by insights gained from reviewing numerous mission-critical applications deployed on Azure. Design for your reliability objectives

Mission critical doesn't mean the same for everyone. The architecture will vary by the workload's business requirements and acceptable downtime. Those are often defined by Service Level Objectives (SLOs), such as 99.9% vs. 99.999% availability. Consider availability objectives to be more than just uptime. They represent consistent service relative to a healthy application state. As a starting point, teams should define how much downtime is acceptable. Use an Uptime/Downtime calculator to determine the tolerable downtime. This design methodology can serve as a starting point for architectural decisions and tradeoffs after objectives have been set.

====================================================================================================
Chunk ID : semantic__p90__well-architected__mission-critical__mission-critical-design-methodology.md__chunk_2
Taille réelle : 1592 caractères
----------------------------------------------------------------------------------------------------
As a draft target architecture takes shape and cost and complexity become clearer, the initial requirements may be revisited, challenged, adjusted, or addressed through alternative solutions. For example, while a single-region, multi-zone setup may suffice for many critical workloads, higher reliability demands more engineering effort and complexity. Avoid defaulting to complex solutions like active-active multi-region unless there are strong requirements to do so. RTO (Recovery Time Objective) and RPO (Recovery Point Objective) are also key in defining reliability needs. For example, if your goal is to recover an application in under a minute, backup-based or active-passive strategies likely won't be fast enough. Refer to
Recommendations for defining reliability targets

Strive for end-to-end automation

Adopt a comprehensive automation strategy that spans both deployment and ongoing management activities. This methodology emphasizes consistency, repeatability, and resilience through automation-first principles. Typical areas for automation are routine tasks, such as patching, scaling, and monitoring, to reduce manual effort and errors. Favor templates for configuration and deployment to ensure consistency and clarity, using scripts only when templates aren't viable. Refer to
Recommendations for enabling automation

Design for zero-downtime deployments

Zero-downtime deployments ensure users don't experience any disruption during changes. This methodology demands rigorous

In [84]:
display_semantic_samples(
    percentile=95,
    number_of_samples=3
)

Stratégie : semantic | Percentile : 95 | Nombre total : 1309

====================================================================================================
Chunk ID : semantic__p95__well-architected__mission-critical__mission-critical-design-methodology.md__chunk_0
Taille réelle : 1659 caractères
----------------------------------------------------------------------------------------------------
Design methodology for mission-critical workloads on Azure

Designing a mission-critical application on any cloud platform demands a thoughtful engineering approach. There's complexity related to: understanding the platform's capabilities, selecting the right services, configuring them correctly, operationalizing them effectively, and staying aligned with evolving best practices and service roadmaps. To navigate this complexity, establish a clear and simple design methodology that aligns with your business requirements, particularly around uptime and recovery. When decision-making becomes challenging or you find yourself stuck in analysis paralysis, return to your methodology as a reference point. It can help validate your choices, keep your design focused, and ensure alignment with your overall goals. This article suggests a design methodology that's informed by insights gained from reviewing numerous mission-critical applications deployed on Azure. Design for your reliability objectives

Mission critical doesn't mean the same for everyone. The architecture will vary by the workload's business requirements and acceptable downtime. Those are often defined by Service Level Objectives (SLOs), such as 99.9% vs. 99.999% availability. Consider availability objectives to be more than just uptime. They represent consistent service relative to a healthy application state. As a starting point, teams should define how much downtime is acceptable. Use an Uptime/Downtime calculator to de

====================================================================================================
Chunk ID : semantic__p95__well-architected__mission-critical__mission-critical-design-methodology.md__chunk_1
Taille réelle : 1592 caractères
----------------------------------------------------------------------------------------------------
As a draft target architecture takes shape and cost and complexity become clearer, the initial requirements may be revisited, challenged, adjusted, or addressed through alternative solutions. For example, while a single-region, multi-zone setup may suffice for many critical workloads, higher reliability demands more engineering effort and complexity. Avoid defaulting to complex solutions like active-active multi-region unless there are strong requirements to do so. RTO (Recovery Time Objective) and RPO (Recovery Point Objective) are also key in defining reliability needs. For example, if your goal is to recover an application in under a minute, backup-based or active-passive strategies likely won't be fast enough. Refer to
Recommendations for defining reliability targets

Strive for end-to-end automation

Adopt a comprehensive automation strategy that spans both deployment and ongoing management activities. This methodology emphasizes consistency, repeatability, and resilience through automation-first principles. Typical areas for automation are routine tasks, such as patching, scaling, and monitoring, to reduce manual effort and errors. Favor templates for configuration and deployment to ensure consistency and clarity, using scripts only when templates aren't viable. Refer to
Recommendations for enabling automation

Design for zero-downtime deployments

Zero-downtime deployments ensure users don't experience any disruption during changes. This methodology demands rigorous

====================================================================================================
Chunk ID : semantic__p95__well-architected__mission-critical__mission-critical-design-methodology.md__chunk_2
Taille réelle : 918 caractères
----------------------------------------------------------------------------------------------------
To support this, deployment tools and processes must be highly available and resilient. Consistency is key. The same artifacts and automated processes should be used across all environments to eliminate any chance of manual errors and reduce overall risk. End-to-end automation isn't just preferred; it's mandatory for achieving reliable, repeatable, and interruption-free deployments. Refer to
Recommendations for deployment and testing

Design for fast failure detection and recovery

Fast failure detection starts with a well-defined health model. Because failures often cascade across components, early detection and clear dependency between workload components are non-negotiable for minimizing the blast radius and speeding up recovery. This means clearly identifying what
healthy
 and
unhealthy
 look like for each component, based on real user flows and business thresholds for performance and availability.

**Sauvegarder les résultats**

In [85]:
semantic_benchmark_df.to_csv(
    OUTPUT_DIR / "semantic_chunking_statistics.csv",
    index=False
)

semantic_validation_df.to_csv(
    OUTPUT_DIR / "semantic_chunking_validation.csv",
    index=False
)

print("Résultats Semantic sauvegardés dans :", OUTPUT_DIR)

Résultats Semantic sauvegardés dans : /content/chunking_benchmark_results

**protocole expérimental**
Corpus Azure (19 documents)
        │
        ▼
9 configurations de chunking
(Fixed / Recursive / Semantic)
        │
        ▼
Embeddings identiques
BAAI/bge-small-en-v1.5
        │
        ▼
9 index FAISS
        │
        ▼
Jeu de questions (Ground Truth)
        │
        ▼
Recherche Top-5
        │
        ▼
Recall@1
Recall@3
Recall@5
MRR
Temps de recherche
        │
        ▼
Choix du meilleur chunking

**Étape 1 — Vérifier les documents disponibles**

In [86]:

print("Nombre d'unités documentaires :", len(documents))
print()

sources = sorted({
    doc.metadata.get("source", "")
    for doc in documents
})

for index, source in enumerate(sources, start=1):
    print(f"{index:02d}. {source}")

Nombre d'unités documentaires : 617

01. azure_serverless_computing_cookbook.pdf
02. en-us-azure-architecture-777fa9b92470.html
03. en-us-azure-architecture-patterns-2da035768373.html
04. en-us_azure_architecture.html
05. en-us_azure_architecture_ai-ml.html
06. en-us_azure_architecture_browse.html
07. en-us_azure_architecture_data-guide.html
08. en-us_azure_architecture_patterns.html
09. enterprise_cloud_strategy.pdf
10. well-architected__ai__design-principles.md
11. well-architected__cost-optimization__cost-model.md
12. well-architected__cost-optimization__design-patterns.md
13. well-architected__cost-optimization__optimize-flow-costs.md
14. well-architected__hpc__hpc-design-principles.md
15. well-architected__microsoft-fabric__reliability.md
16. well-architected__mission-critical__mission-critical-design-methodology.md
17. well-architected__service-guides__azure-databricks.md
18. well-architected__sustainability__overview.md
19. well-architected__sustainability__sustainability-cost-optimization-recommendations.md

**Étape 2 — Fonction pour explorer un document:**
****
Cette fonction permet d’afficher le contenu d’un fichier afin de créer des questions fondées sur son contenu réel.

In [87]:
def inspect_source(
    source_keyword: str,
    max_characters: int = 5000,
    start_unit: int = 0,
    max_units: int = 3
) -> None:
    """
    Affiche une partie des unités documentaires correspondant
    à une source.

    Utile notamment pour les PDF composés de nombreuses pages.
    """

    matching_documents = [
        doc
        for doc in documents
        if source_keyword.lower()
        in str(
            doc.metadata.get("source", "")
        ).lower()
    ]

    print(
        "Unités documentaires trouvées :",
        len(matching_documents)
    )

    selected_documents = matching_documents[
        start_unit:start_unit + max_units
    ]

    if not selected_documents:
        print("Aucune unité dans cet intervalle.")
        return

    for index, doc in enumerate(
        selected_documents,
        start=start_unit + 1
    ):
        print("\n" + "=" * 100)
        print("Unité :", index)
        print("Source :", doc.metadata.get("source"))
        print("Format :", doc.metadata.get("format"))
        print("Titre :", doc.metadata.get("title", ""))
        print("Page :", doc.metadata.get("page", "N/A"))
        print("-" * 100)
        print(doc.page_content[:max_characters])

In [88]:
inspect_source(
    "sustainability__overview",
    max_characters=4000,
    max_units=1
)
inspect_source(
    "azure-databricks",
    max_characters=4000,
    max_units=1
)
inspect_source(
    "enterprise_cloud_strategy",
    max_characters=3500,
    start_unit=0,
    max_units=3
)
inspect_source(
    "enterprise_cloud_strategy",
    max_characters=3500,
    start_unit=50,
    max_units=3
)

Unités documentaires trouvées : 1

====================================================================================================
Unité : 1
Source : well-architected__sustainability__overview.md
Format : markdown
Titre : Sustainable workloads on Azure
Page : N/A
----------------------------------------------------------------------------------------------------
Sustainable workloads on Azure

Sustainability for workloads in the cloud is a shared responsibility between the cloud provider and the organization. Azure workloads are carbon neutral and use 100% renewable energy. Microsoft also protects more land. By running a workload in Azure, you're already on the path to sustainability compared to running it on-premises, which can be between 50-98% less carbon efficient.

As a cloud solution architect, your design decisions directly shape how efficiently a workload uses cloud resources. Without deliberate design choices, a workload can consume avoidable energy over time and become an environmental burden as it scales.

This guidance helps you design sustainability into your architecture from the start. It focuses on the key design and operational choices you make in real systems and how to navigate them while maintaining reliability, security, and performance. You learn how common architectural decisions influence resource consumption, where inefficiencies typically emerge, and how to reduce waste without compromising system quality.

What is a sustainable workload?

Sustainability has become a critical cloud architecture concern as hyperscale datacenters continue to expand, AI workloads drive unprecedented energy demand, and organizations accumulate always-on infrastructure that often operates far below capacity. Modern cloud environments frequently suffer from sprawl: idle virtual machines, oversized Kubernetes clusters, excessive telemetry, and unnecessary data replication all consume energy without delivering meaningful business value.

A sustainable workload is designed to minimize unnecessary resource consumption while still meeting business, reliability, security, and performance requirements. Sustainability isn't a separate architectural discipline; it's closely tied to the same engineering decisions that shape resilient, secure, and efficient systems. Workloads that are optimized for utilization, scalability, and operational efficiency are typically more sustainable because they reduce wasted compute, storage, and network resources.

Sustainability strongly overlaps with the Cost Optimization pillar of the Azure Well-Architected Framework. Right-sizing infrastructure, using autoscaling effectively, and eliminating idle or redundant resources all improve cloud efficiency while also reducing unnecessary energy consumption and carbon emissions. In many cases, the first step toward sustainability is simply removing waste from the system.

:::image type="content" source="./images/sustainability-shared-responsibility-cloud-efficiency.png" alt-text="Diagram showing how to achieve cloud efficiency." border="false" lightbox="./images/sustainability-shared-responsibility-cloud-efficiency.png":::

[!IMPORTANT]
Sustainability extends beyond cost efficiencies. Every design decision, whether functional or non-functional, can impact carbon emission.

A workload can be inexpensive to operate while still being environmentally inefficient. Excessive telemetry collection, poorly optimized application flows, unnecessary data movement, inefficient APIs, or over-engineered resiliency patterns can all contribute to the environmental footprint of a workload even if infrastructure costs appear acceptable.

What are the common challenges?

Designing sustainable workloads is often difficult because sustainability introduces a new set of architectural tradeoffs that extend beyond traditional concerns like cost, reliability, and performance. While many sustainability improvements align with cloud efficiency, they also require organizations to rethink how applications are designed, operated, and measured.

Challenge and description

Sustainability impact

Balancing sustainability with reliability.
 Highly resilient systems often require redundancy, replication, and excess capacity through multiregion deployments or active-active architectures.

Increased infrastructure usage and energy consumption from ove
Unités documentaires trouvées : 1

====================================================================================================
Unité : 1
Source : well-architected__service-guides__azure-databricks.md
Format : markdown
Titre : Architecture Best Practices for Azure Databricks
Page : N/A
----------------------------------------------------------------------------------------------------
Architecture best practices for Azure Databricks

Azure Databricks is an Apache Spark-based analytics platform that data teams can use to collaborate efficiently. Use it to build and deploy data engineering, machine learning, and analytics workloads at scale. This article covers common considerations and best practices for Azure Databricks and gives architectural recommendations mapped to the
Azure Well-Architected Framework pillars
.

It's assumed that as an architect, you've reviewed
Choose an analytical data store
 and chose Azure Databricks as the analytics platform for your workload.

Technology scope

This review focuses on the interrelated decisions for the following Azure resources:

Azure Databricks

Spark

Delta Lake

Unity Catalog

MLflow

Reliability

The purpose of the Reliability pillar is to provide continued functionality by
building enough resilience and the ability to recover fast from failures
.

Reliability design principles
 provide a high-level design strategy applied for individual components, system flows, and the system as a whole.

Workload design checklist

Start your design strategy based on the
design review checklist for Reliability
. Determine its relevance to your business requirements while keeping in mind the nature of your application and the criticality of its components. Extend the strategy to include more approaches as needed.

[!div class="checklist"]

Understand service limits and quotas.
 Azure Databricks
service limits
 directly constrain workload reliability through compute clusters, workspace capacity, storage throughput, and network bandwidth restrictions. Your architecture design must proactively incorporate quotas to prevent unexpected service disruptions that can halt scaling operations during peak demand. These quotas include a 1000-node cluster limit, workspace cluster maximums, and regional capacity constraints.

Use failure mode analysis (FMA) to anticipate potential failures.
 Systematic
FMA
 identifies potential system failures and establishes corresponding mitigation strategies to maintain distributed computing resilience.

The following table includes common failure scenarios and their proven mitigation approaches.

Failure

Mitigation

Cluster driver node failure

Use cluster automatic-restart policies and implement checkpointing for Spark applications. Use structured streaming with fault-tolerant state management.

Job execution failures

Implement retry policies with exponential backoff. Use Azure Databricks job orchestration with error handling. Set up appropriate timeout settings.

Data corruption or inconsistency

Use Delta Lake atomicity, consistency, isolation, and durability (ACID) transactions, time travel capabilities, and data expectations in Lakeflow Spark Declarative Pipelines. Implement data validation checks and monitoring.

Workspace or region unavailability

Implement multiregion deployment strategies. Use workspace backup and restore procedures. Set up cross-region data replication.

These mitigation strategies use native Azure Databricks capabilities like automatic restart, automatic scaling, Delta Lake consistency guarantees, and Unity Catalog security features for fault tolerance.

Design to support redundancy across the critical layers.
 Redundancy in the critical architectural layers is key to maintaining workload continuity.

For example, distribute clusters across availability zones by using diverse instance types and cluster pools and by implementing automatic node replacement policies. Reliable network design also protects against connectivity failures that can disrupt control plane reachability, data access, and communication with dependencies. Use redundant network paths, diverse private endpoint configurations, Domain Name System (DNS) failover mechanisms, and virtual network injection to achieve network resilience. Metadata resilience is important for maintaining compliance and data accessibility during service disruptions because go
Unités documentaires trouvées : 156

====================================================================================================
Unité : 1
Source : enterprise_cloud_strategy.pdf
Format : pdf
Titre : enterprise_cloud_strategy
Page : 1
----------------------------------------------------------------------------------------------------
Enterprise Cloud Strategy
2nd Edition
Microsoft Press
Barry Briggs
Eduardo Kassner

====================================================================================================
Unité : 2
Source : enterprise_cloud_strategy.pdf
Format : pdf
Titre : enterprise_cloud_strategy
Page : 2
----------------------------------------------------------------------------------------------------
PUBLISHED BY
Microsoft Press
A division of Microsoft Corporation
One Microsoft Way
Redmond, Washington 98052-6399
Copyright © 2017 by Microsoft Corporation
All rights reserved. No part of the contents of this book may be reproduced or transmitted in any
form or by any means without the written permission of the publisher.
Microsoft Press books are available through booksellers and distributors worldwide. If you need
support related to this book, email Microsoft Press Support at mspinput@microsoft.com. Please tell us
what you think of this book at http://aka.ms/tellpress.
This book is provided “as-is” and expresses the author’s views and opinions. The views, opinions and
information expressed in this book, including URL and other Internet website references, may change
without notice.
Some examples depicted herein are provided for illustration only and are fictitious. No real association
or connection is intended or should be inferred.
Microsoft and the trademarks listed at http://www.microsoft.com on the “Trademarks” webpage are
trademarks of the Microsoft group of companies. All other marks are property of their respective
owners.
Acquisitions Editor: Janine Patrick
Developmental Editor: Bob Russell, Octal Publishing, Inc.
Editorial Production: Dianne Russell, Octal Publishing, Inc.
Copyeditor: Bob Russell

====================================================================================================
Unité : 3
Source : enterprise_cloud_strategy.pdf
Format : pdf
Titre : enterprise_cloud_strategy
Page : 3
----------------------------------------------------------------------------------------------------
Defining correct enterprise cloud strategy is a complex task that is easy to understand but hard to
master. That is why the Enterprise Cloud Strategy book represents one of the best publications for
cloud experts who want to learn how to shape the efficient enterprise cloud transformation. This book
provides a clear yet deep level of detail on all aspects of cloud strategy, offering a large collection of
case studies and repeatable patterns, and even providing cloud architectural blueprints to accelerate
specific cloud use cases. It is a perfect companion for all advisors, strategists, and enterprise planners
that are shaping complex cloud journey roadmaps—and is mandatory reading for all our technology
strategy professionals. It is important that the book covers nontechnology aspects of cloud strategy,
but it is even more important that it guides cloud strategy implementations. And above all, it is very
pleasant to read and won’t deter any cloud novices.
—Miha Kralj, managing director of cloud strategy, Accenture
The move to the cloud has opened many opportunities. With it comes the need for best practices and
guidance of how to adopt cloud platforms with enterprise grade rigor and governance. This book fills
this much-needed gap in a clear, concise, and practical way. It is an easy read, too. It is based on best
practices of Microsoft IT and many global companies, therefore I recommend you review the
approach, practices. I wish you the best of luck in your journey.
—Gavriella Schuster, corporate vice president, One Commercial Partner,
Microsoft Corporation, July 2017
The Enterprise Cloud Strategy book provides a strategic and, more important, end-to-end perspective
on the multitudes of concerns, challenges, and, most crucial, opportunities for enterprises in the age
of cloud computing. From strategic reasoning, to practical guidance to assess needs and explore
proven practices, this book shows the enterprise architect or executive what cloud computing is all
about and why any modern enterprise needs to care now.
—Ulrich Homann, distinguished architect, Cloud + Enterprise Engineering, Microsoft
Unités documentaires trouvées : 156

====================================================================================================
Unité : 51
Source : enterprise_cloud_strategy.pdf
Format : pdf
Titre : enterprise_cloud_strategy
Page : 51
----------------------------------------------------------------------------------------------------
37
CHAPTER 5 | Building the capability

scripts or applications in the cloud, making them cloud developers, as well. And, operations personnel
will less and less manage hardware assets such as servers and networks, and more and more handle
creating automated configuration, deployment scripts, insight portals, monitoring scripts, and
orchestration flows, or using those provided by the cloud or tools vendor. (We cover DevOps in more
detail in Chapter 7.)
Lastly, the information architect will ensure both the consistency of data models across the enterprise
and their life cycle. A well-designed, documented, and maintained set of models—for example, for
“customer” and “product” data entities—ensure ease of system integration and consistency of
reporting, among other benefits.
The human resources team should work with the relevant leaders to build readiness and training plans
for the affected individuals. Nearly all roles in IT will evolve. Many will require specialized training; for
example, in new tools or new processes.
Skills development
Think about building cloud readiness in phases, with increasing levels of education and rigor. One
framework that you can use encompasses three phases of training, which you can see in Figure 5-6:
beginning with educating individuals, and then building a cloud practice; that is, teams of educated
engineers, and then using them to educate the entire organization.

Figure 5-6: Building skills
In the first phase (Figure 5-7), drive technical acumen for individuals by having them attend classes
either online or in person.

Figure 5-7: Driving technical acumen
Numerous free or inexpensive online courses for Azure exist, both on the Azure website
(https://azure.microsoft.com/en-us/community/training/) as well as through the Microsoft Virtual
Academy. You also can find a comprehensive set of training resources available for Microsoft partners
in the Azure Skills Initiative (https://blogs.partner.microsoft.com/mpn/new-cloud-trainings-for-next-
generation-tech-professionals/), and many other organizations provide similar types of training.
These courses help individuals learn the basic skills for the cloud. Other forms of training, such as
those shown in Figure 5-8, help your teams develop common sets of skills and the beginnings of your
cloud practice.

====================================================================================================
Unité : 52
Source : enterprise_cloud_strategy.pdf
Format : pdf
Titre : enterprise_cloud_strategy
Page : 52
----------------------------------------------------------------------------------------------------
38
CHAPTER 5 | Building the capability


Figure 5-8: Building your cloud practice
Immersion experiences such as boot camps bring teams together for a full-day immersion in the
cloud as it applies to their organization, and participating in any of the large numbers of communities
can further deepen your team’s skills.
Of course, there’s nothing like doing, as they say, either by leading or helping a team build and deploy
cloud applications (Figure 5-9), or by simply being in a cloud-centric role.

Figure 5-9 Growing the capability of your team
What kinds of training should you have your teams participate in? Here is a sample catalog of courses
provided by Microsoft, and this list, incidentally, will help you build the specific cloud roles we
mentioned in Figure 5-10.

Figure 5-10 Types of training available for Azure

====================================================================================================
Unité : 53
Source : enterprise_cloud_strategy.pdf
Format : pdf
Titre : enterprise_cloud_strategy
Page : 53
----------------------------------------------------------------------------------------------------
39
CHAPTER 5 | Building the capability

By taking a thoughtful approach to skills development, you not only can provide the requisite training
to individuals in your organization, you also can improve the overall effectiveness of entire teams.
Applications teams
Applications teams must be consulted on a range of topics. Typically, it is these teams that will
provide the required information for the application catalog or portfolio management system
(discussed later) that will help prioritize application migration.
In addition, discuss with them the technical implications of running their applications in the cloud.
If an application is “chatty” in the datacenter (meaning it sends and receives a lot of messages
to accomplish a task) it’s possible that the latency inherent in moving to an off-premises cloud
datacenter will amplify delays. To ameliorate this, application teams might either want to update the
application or recommend using a high-speed dedicated line to provide additional bandwidth. If
you’re using a cloud database, it might impose certain size restrictions, but this can be addressed by
using specific approaches such as database sharding (a database shard is a partition of data in a
database; each shard is commonly hosted on a separate database server instance).
Applications teams should know the longer-term possibilities of a cloud-centric application. For
example, redesigning an application to be PaaS or to be a collection of microservices (discussed in
more detail in Chapter 11) will require awareness and training.
From a methodology perspective, applications teams should consider whether using a traditional
waterfall approach (as shown in Figure 5-11) is appropriate, or whether you can use an Agile
methodology—incorporating many short development sprints with feedback and potential course
correction. For certain types of applications (e.g., financial accounting, for which strict regulatory
requirements can essentially dictate the functional specification) you might use a waterfall approach.
Waterfall-based projects usually include a detailed, comprehensive requirements document that
project managers can validate.

Figure 5-11: Traditional waterfall approach to software development
However, fewer applications today require this amount of rigor and most actually benefit by short
amounts of development followed by user testing and feedback, which is a hallmark of Agile
development (see Figure 5-12). In this way, users can get a sense of the application, request new
features, suggest others be removed, and so on. In many cases, the Agile methodology leads to a

**Étape 3 — Créer les premières questions vérifiées**

In [89]:
evaluation_questions = [
    {
        "id": "Q001",
        "question": (
            "Who shares responsibility for the sustainability "
            "of cloud workloads?"
        ),
        "answer": (
            "The responsibility is shared between the cloud provider "
            "and the organization."
        ),
        "expected_source": (
            "markdown\\well-architected__sustainability__overview.md"
        ),
        "gold_evidence": (
            "Sustainability for workloads in the cloud is a shared "
            "responsibility between the cloud provider and the organization."
        )
    },

    {
        "id": "Q002",
        "question": (
            "How much less carbon efficient can on-premises workloads "
            "be compared with Azure workloads?"
        ),
        "answer": (
            "On-premises workloads can be between 50% and 98% "
            "less carbon efficient."
        ),
        "expected_source": (
            "markdown\\well-architected__sustainability__overview.md"
        ),
        "gold_evidence": (
            "running it on-premises, which can be between "
            "50-98% less carbon efficient"
        )
    },

    {
        "id": "Q003",
        "question": (
            "How do architecture decisions influence the sustainability "
            "of an Azure workload?"
        ),
        "answer": (
            "Architecture decisions determine how efficiently "
            "the workload uses cloud resources."
        ),
        "expected_source": (
            "markdown\\well-architected__sustainability__overview.md"
        ),
        "gold_evidence": (
            "your design decisions directly shape how efficiently "
            "a workload uses cloud resources"
        )
    },

    {
        "id": "Q004",
        "question": (
            "What is a sustainable cloud workload?"
        ),
        "answer": (
            "It is a workload designed to minimize unnecessary resource "
            "consumption while meeting business, reliability, security, "
            "and performance requirements."
        ),
        "expected_source": (
            "markdown\\well-architected__sustainability__overview.md"
        ),
        "gold_evidence": (
            "A sustainable workload is designed to minimize unnecessary "
            "resource consumption while still meeting business, reliability, "
            "security, and performance requirements."
        )
    },

    {
        "id": "Q005",
        "question": (
            "Which infrastructure practices can improve both cost "
            "optimization and sustainability?"
        ),
        "answer": (
            "Right-sizing infrastructure, using autoscaling effectively, "
            "and removing idle or redundant resources."
        ),
        "expected_source": (
            "markdown\\well-architected__sustainability__overview.md"
        ),
        "gold_evidence": (
            "Right-sizing infrastructure, using autoscaling effectively, "
            "and eliminating idle or redundant resources"
        )
    },

    {
        "id": "Q006",
        "question": (
            "What type of analytics platform is Azure Databricks?"
        ),
        "answer": (
            "Azure Databricks is an Apache Spark-based analytics platform."
        ),
        "expected_source": (
            "markdown\\well-architected__service-guides__"
            "azure-databricks.md"
        ),
        "gold_evidence": (
            "Azure Databricks is an Apache Spark-based analytics platform"
        )
    },

    {
        "id": "Q007",
        "question": (
            "What types of workloads can teams build with Azure Databricks?"
        ),
        "answer": (
            "Teams can build data engineering, machine learning, "
            "and analytics workloads."
        ),
        "expected_source": (
            "markdown\\well-architected__service-guides__"
            "azure-databricks.md"
        ),
        "gold_evidence": (
            "build and deploy data engineering, machine learning, "
            "and analytics workloads at scale"
        )
    },

    {
        "id": "Q008",
        "question": (
            "Which Azure technologies are included in the scope "
            "of the Azure Databricks architecture review?"
        ),
        "answer": (
            "Azure Databricks, Spark, Delta Lake, Unity Catalog, "
            "and MLflow."
        ),
        "expected_source": (
            "markdown\\well-architected__service-guides__"
            "azure-databricks.md"
        ),
        "gold_evidence": (
            "Azure Databricks\n\nSpark\n\nDelta Lake\n\nUnity Catalog\n\nMLflow"
        )
    },

    {
        "id": "Q009",
        "question": (
            "What is the purpose of the Reliability pillar?"
        ),
        "answer": (
            "Its purpose is to provide continued functionality by building "
            "resilience and enabling fast recovery from failures."
        ),
        "expected_source": (
            "markdown\\well-architected__service-guides__"
            "azure-databricks.md"
        ),
        "gold_evidence": (
            "The purpose of the Reliability pillar is to provide continued "
            "functionality by building enough resilience and the ability "
            "to recover fast from failures"
        )
    },

    {
        "id": "Q010",
        "question": (
            "How should Azure Databricks job execution failures be handled?"
        ),
        "answer": (
            "They should be handled with retry policies using exponential "
            "backoff, error handling, and appropriate timeout settings."
        ),
        "expected_source": (
            "markdown\\well-architected__service-guides__"
            "azure-databricks.md"
        ),
        "gold_evidence": (
            "Implement retry policies with exponential backoff. "
            "Use Azure Databricks job orchestration with error handling. "
            "Set up appropriate timeout settings."
        )
    }
]

additional_questions = [

    # ========================================================
    # Q011 à Q012 : 2 questions Markdown
    # ========================================================

    {
        "id": "Q011",
        "question": (
            "What is a cost model in the Azure "
            "Well-Architected Framework?"
        ),
        "answer": (
            "A cost model is an estimate that predicts the combined "
            "costs of services and their associated expenses."
        ),
        "expected_source": (
            "markdown\\well-architected__cost-optimization__"
            "cost-model.md"
        ),
        "gold_evidence": (
            "A cost model is an estimate that predicts the combined "
            "costs of services and their associated expenses."
        )
    },

   {
    "id": "Q012",
    "question": (
        "Which events can interrupt long-running HPC jobs?"
    ),
    "answer": (
        "Long-running HPC jobs can be interrupted by infrastructure "
        "failures, spot evictions, and maintenance events."
    ),
    "expected_source": (
        "markdown\\well-architected__hpc__"
        "hpc-design-principles.md"
    ),
    "gold_evidence": (
        "Long-running HPC jobs are vulnerable to infrastructure "
        "failures, spot evictions, and maintenance events."
    )
},
    # ========================================================
    # Q013 à Q022 : 10 questions HTML
    # ========================================================

    {
        "id": "Q013",
        "question": (
            "What kinds of resources are included in the "
            "Azure Architecture Center?"
        ),
        "answer": (
            "It includes solution ideas, example workloads, reference "
            "architectures, technology decision guides, and architecture "
            "guides."
        ),
        "expected_source": (
            "html\\en-us-azure-architecture-777fa9b92470.html"
        ),
        "gold_evidence": (
            "Azure Architecture Center is a catalog of solution ideas, "
            "example workloads, reference architectures, technology "
            "decision guides, and architecture guides for Azure workloads."
        )
    },

    {
        "id": "Q014",
        "question": (
            "What does the Azure Architecture Center help architects "
            "explore when building Azure workloads?"
        ),
        "answer": (
            "It helps architects explore best practices and patterns "
            "for building workloads on Microsoft Azure."
        ),
        "expected_source": (
            "html\\en-us-azure-architecture-777fa9b92470.html"
        ),
        "gold_evidence": (
            "Explore best practices and patterns for building workloads "
            "on Microsoft Azure."
        )
    },

    {
        "id": "Q015",
        "question": (
            "What capabilities does Microsoft Foundry provide "
            "for generative AI development?"
        ),
        "answer": (
            "It provides access to a model catalog, agent hosting, "
            "fine-tuning, evaluation tools, and responsible AI capabilities."
        ),
        "expected_source": (
            "html\\en-us_azure_architecture_ai-ml.html"
        ),
        "gold_evidence": (
            "Microsoft Foundry provides access to a model catalog, "
            "agent hosting through Foundry Agent Service, fine-tuning, "
            "evaluation tools, and responsible AI capabilities."
        )
    },

    {
        "id": "Q016",
        "question": (
            "Which open-source frameworks are supported by "
            "Azure Machine Learning?"
        ),
        "answer": (
            "Azure Machine Learning supports PyTorch, TensorFlow, "
            "and scikit-learn."
        ),
        "expected_source": (
            "html\\en-us_azure_architecture_ai-ml.html"
        ),
        "gold_evidence": (
            "Azure Machine Learning supports open-source frameworks "
            "like PyTorch, TensorFlow, and scikit-learn."
        )
    },

    {
        "id": "Q017",
        "question": (
            "What type of platform is Microsoft Copilot Studio?"
        ),
        "answer": (
            "It is a low-code platform for building, customizing, "
            "and deploying AI-powered agents."
        ),
        "expected_source": (
            "html\\en-us_azure_architecture_ai-ml.html"
        ),
        "gold_evidence": (
            "A low-code platform for building, customizing, "
            "and deploying AI-powered agents."
        )
    },

    {
        "id": "Q018",
        "question": (
            "Which factors should be considered when choosing "
            "a database for an Azure workload?"
        ),
        "answer": (
            "The choice depends on the data model, consistency requirements, "
            "query patterns, and operational preferences."
        ),
        "expected_source": (
            "html\\en-us_azure_architecture_data-guide.html"
        ),
        "gold_evidence": (
            "The right database for your scenario depends on your "
            "data model, consistency requirements, query patterns, "
            "and operational preferences."
        )
    },

    {
        "id": "Q019",
        "question": (
            "Which database deployment models are included "
            "in the Azure database portfolio?"
        ),
        "answer": (
            "The portfolio includes PaaS offerings, IaaS options, "
            "and specialized services for specific workload patterns."
        ),
        "expected_source": (
            "html\\en-us_azure_architecture_data-guide.html"
        ),
        "gold_evidence": (
            "The Azure database portfolio spans fully managed platform "
            "as a service (PaaS) offerings, infrastructure as a service "
            "(IaaS) options, and specialized services for specific "
            "workload patterns."
        )
    },

    {
        "id": "Q020",
        "question": (
            "Why can Azure cloud design patterns be used outside Azure?"
        ),
        "answer": (
            "They are technology-agnostic and are suitable for any "
            "distributed system."
        ),
        "expected_source": (
            "html\\en-us_azure_architecture_patterns.html"
        ),
        "gold_evidence": (
            "The following cloud design patterns are technology-agnostic, "
            "which makes them suitable for any distributed system."
        )
    },

    {
        "id": "Q021",
        "question": (
            "What should guide the selection of a cloud design pattern?"
        ),
        "answer": (
            "The pattern should be selected according to the problem "
            "that needs to be solved, not according to the technology."
        ),
        "expected_source": (
            "html\\en-us_azure_architecture_patterns.html"
        ),
        "gold_evidence": (
            "Choose a pattern based on the problem you need to solve, "
            "not the technology you want to use."
        )
    },

    {
        "id": "Q022",
        "question": (
            "What information can users find when browsing "
            "Azure architectures?"
        ),
        "answer": (
            "They can find architecture diagrams, technology descriptions, "
            "real-world examples, and solution ideas."
        ),
        "expected_source": (
            "html\\en-us_azure_architecture_browse.html"
        ),
        "gold_evidence": (
            "Find architecture diagrams and technology descriptions "
            "for reference architectures, real world examples of cloud "
            "architectures, and solution ideas for common workloads on Azure."
        )
    },

    # ========================================================
    # Q023 à Q026 : enterprise_cloud_strategy.pdf
    # ========================================================

    {
        "id": "Q023",
        "question": (
            "Does cloud adoption require an organization to move "
            "all applications out of its local datacenter?"
        ),
        "answer": (
            "No. Some applications can remain in a local datacenter "
            "while others are moved to the cloud."
        ),
        "expected_source": (
            "pdf\\enterprise_cloud_strategy.pdf"
        ),
        "gold_evidence": (
            "the cloud is not an “either/or” proposition. It is certainly "
            "possible, and indeed in many cases desirable, to leave some "
            "applications running in a local, traditional datacenter while "
            "others are moved to the cloud."
        )
    },

    {
        "id": "Q024",
        "question": (
            "What are the five modernization approaches described "
            "in Enterprise Cloud Strategy?"
        ),
        "answer": (
            "They are retire, replace, retain and wrap, rehost, "
            "and reenvision."
        ),
        "expected_source": (
            "pdf\\enterprise_cloud_strategy.pdf"
        ),
        "gold_evidence": (
            "the most convenient way to think about modernization, "
            "which is commonly called “the five R’s”"
        )
    },

    {
        "id": "Q025",
        "question": (
            "What does rehosting a legacy application involve?"
        ),
        "answer": (
            "It involves keeping the same basic functionality while "
            "moving the application to the cloud."
        ),
        "expected_source": (
            "pdf\\enterprise_cloud_strategy.pdf"
        ),
        "gold_evidence": (
            "Rehosting involves keeping the same basic functionality, "
            "but moving it to the cloud where it is easier to manage "
            "and less expensive to run."
        )
    },

    {
        "id": "Q026",
        "question": (
            "What initial responsibility was assigned to the "
            "Cloud Strategy Team?"
        ),
        "answer": (
            "The team was responsible for leading cloud analysis "
            "and experimentation."
        ),
        "expected_source": (
            "pdf\\enterprise_cloud_strategy.pdf"
        ),
        "gold_evidence": (
            "The Cloud Strategy Team was chartered to lead the cloud "
            "analysis and experimentation phase previously described "
            "(see Figure 5-2)."
        )
    },

    # ========================================================
    # Q027 à Q030 : azure_serverless_computing_cookbook.pdf
    # ========================================================

    {
        "id": "Q027",
        "question": (
            "What type of storage service is Azure Table Storage?"
        ),
        "answer": (
            "It is a NoSQL key-value persistent medium for storing "
            "semi-structured data."
        ),
        "expected_source": (
            "pdf\\azure_serverless_computing_cookbook.pdf"
        ),
        "gold_evidence": (
            "Azure Table storage, a NoSQL key-value persistent medium "
            "for storing semi-structured data."
        )
    },

    {
        "id": "Q028",
        "question": (
            "How does a SendGrid output binding authenticate "
            "when sending emails?"
        ),
        "answer": (
            "It uses the API key stored in the application settings."
        ),
        "expected_source": (
            "pdf\\azure_serverless_computing_cookbook.pdf"
        ),
        "gold_evidence": (
            "The SendGrid output (message) bindings will use the API key "
            "provided in the App settings to invoke the required APIs "
            "of the SendGrid library in order to send the emails."
        )
    },

    {
        "id": "Q029",
        "question": (
            "What kind of Azure service is Azure Data Factory?"
        ),
        "answer": (
            "Azure Data Factory is a cloud-native serverless solution "
            "from Microsoft Azure."
        ),
        "expected_source": (
            "pdf\\azure_serverless_computing_cookbook.pdf"
        ),
        "gold_evidence": (
            "Azure Data Factory is another cloud-native serverless "
            "solution from Microsoft Azure."
        )
    },

    {
        "id": "Q030",
        "question": (
            "Why can precompiled Azure Functions provide "
            "better performance?"
        ),
        "answer": (
            "They do not need to be compiled dynamically during execution."
        ),
        "expected_source": (
            "pdf\\azure_serverless_computing_cookbook.pdf"
        ),
        "gold_evidence": (
            "Precompiled functions have better performance, "
            "as they aren't required to be compiled on the fly."
        )
    }
]


evaluation_questions.extend(
    additional_questions
)

print(
    "Nombre total de questions :",
    len(evaluation_questions)
)

Nombre total de questions : 30

**Étape 4 — Créer le DataFrame**

In [90]:
import pandas as pd
from pathlib import Path


evaluation_df = pd.DataFrame(
    evaluation_questions
)


def canonical_source(source: str) -> str:
    """
    Normalise les chemins Windows/Linux et retourne
    uniquement le nom du fichier.
    """

    normalized_source = str(source).replace(
        "\\",
        "/"
    )

    return Path(normalized_source).name


def detect_format(source: str) -> str:
    """
    Détermine le format à partir du chemin ou de l'extension.
    """

    normalized_source = str(source).lower()

    if normalized_source.endswith(".md"):
        return "markdown"

    if normalized_source.endswith(".html"):
        return "html"

    if normalized_source.endswith(".pdf"):
        return "pdf"

    return "unknown"


evaluation_df["expected_source_canonical"] = (
    evaluation_df["expected_source"]
    .apply(canonical_source)
)

evaluation_df["format"] = (
    evaluation_df["expected_source"]
    .apply(detect_format)
)


EVALUATION_DIR = Path(
    "/content/evaluation"
)

EVALUATION_DIR.mkdir(
    parents=True,
    exist_ok=True
)

evaluation_path = (
    EVALUATION_DIR
    / "chunking_evaluation_30_questions.csv"
)


print(
    "Nombre total de questions :",
    len(evaluation_df)
)

print("\nRépartition par format :")

print(
    evaluation_df["format"]
    .value_counts()
)

Nombre total de questions : 30

Répartition par format :
format
markdown    12
html        10
pdf          8
Name: count, dtype: int64

**Étape 5 — Vérifier les sources**

In [91]:
available_sources = {
    canonical_source(
        doc.metadata.get("source", "")
    )
    for doc in documents
}


evaluation_df["source_exists"] = (
    evaluation_df[
        "expected_source_canonical"
    ]
    .isin(available_sources)
)


source_validation_df = evaluation_df[
    [
        "id",
        "format",
        "expected_source",
        "expected_source_canonical",
        "source_exists"
    ]
]


display(source_validation_df)


missing_sources_df = evaluation_df[
    evaluation_df["source_exists"] == False
]


print(
    "Sources introuvables :",
    len(missing_sources_df)
)

if not missing_sources_df.empty:
    display(
        missing_sources_df[
            [
                "id",
                "expected_source",
                "expected_source_canonical"
            ]
        ]
    )

,id,format,expected_source,expected_source_canonical,source_exists
0,Q001,markdown,markdown\well-architected__sustainability__ove...,well-architected__sustainability__overview.md,True
1,Q002,markdown,markdown\well-architected__sustainability__ove...,well-architected__sustainability__overview.md,True
2,Q003,markdown,markdown\well-architected__sustainability__ove...,well-architected__sustainability__overview.md,True
3,Q004,markdown,markdown\well-architected__sustainability__ove...,well-architected__sustainability__overview.md,True
4,Q005,markdown,markdown\well-architected__sustainability__ove...,well-architected__sustainability__overview.md,True
5,Q006,markdown,markdown\well-architected__service-guides__azu...,well-architected__service-guides__azure-databr...,True
6,Q007,markdown,markdown\well-architected__service-guides__azu...,well-architected__service-guides__azure-databr...,True
7,Q008,markdown,markdown\well-architected__service-guides__azu...,well-architected__service-guides__azure-databr...,True
8,Q009,markdown,markdown\well-architected__service-guides__azu...,well-architected__service-guides__azure-databr...,True
9,Q010,markdown,markdown\well-architected__service-guides__azu...,well-architected__service-guides__azure-databr...,True
10,Q011,markdown,markdown\well-architected__cost-optimization__...,well-architected__cost-optimization__cost-mode...,True
11,Q012,markdown,markdown\well-architected__hpc__hpc-design-pri...,well-architected__hpc__hpc-design-principles.md,True
12,Q013,html,html\en-us-azure-architecture-777fa9b92470.html,en-us-azure-architecture-777fa9b92470.html,True
13,Q014,html,html\en-us-azure-architecture-777fa9b92470.html,en-us-azure-architecture-777fa9b92470.html,True
14,Q015,html,html\en-us_azure_architecture_ai-ml.html,en-us_azure_architecture_ai-ml.html,True
15,Q016,html,html\en-us_azure_architecture_ai-ml.html,en-us_azure_architecture_ai-ml.html,True
16,Q017,html,html\en-us_azure_architecture_ai-ml.html,en-us_azure_architecture_ai-ml.html,True
17,Q018,html,html\en-us_azure_architecture_data-guide.html,en-us_azure_architecture_data-guide.html,True
18,Q019,html,html\en-us_azure_architecture_data-guide.html,en-us_azure_architecture_data-guide.html,True
19,Q020,html,html\en-us_azure_architecture_patterns.html,en-us_azure_architecture_patterns.html,True
20,Q021,html,html\en-us_azure_architecture_patterns.html,en-us_azure_architecture_patterns.html,True
21,Q022,html,html\en-us_azure_architecture_browse.html,en-us_azure_architecture_browse.html,True
22,Q023,pdf,pdf\enterprise_cloud_strategy.pdf,enterprise_cloud_strategy.pdf,True
23,Q024,pdf,pdf\enterprise_cloud_strategy.pdf,enterprise_cloud_strategy.pdf,True
24,Q025,pdf,pdf\enterprise_cloud_strategy.pdf,enterprise_cloud_strategy.pdf,True
25,Q026,pdf,pdf\enterprise_cloud_strategy.pdf,enterprise_cloud_strategy.pdf,True
26,Q027,pdf,pdf\azure_serverless_computing_cookbook.pdf,azure_serverless_computing_cookbook.pdf,True
27,Q028,pdf,pdf\azure_serverless_computing_cookbook.pdf,azure_serverless_computing_cookbook.pdf,True
28,Q029,pdf,pdf\azure_serverless_computing_cookbook.pdf,azure_serverless_computing_cookbook.pdf,True
29,Q030,pdf,pdf\azure_serverless_computing_cookbook.pdf,azure_serverless_computing_cookbook.pdf,True

Sources introuvables : 0

**Étape 6 — Vérifier les passages de référence**

In [92]:
import re
import unicodedata


def normalize_for_matching(text: str) -> str:
    """
    Normalise le texte pour ignorer :
    - les majuscules/minuscules ;
    - les espaces multiples ;
    - les retours à la ligne ;
    - les variantes Unicode ;
    - les différents types de tirets.
    """

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    ).lower()

    # Uniformiser les tirets Unicode
    text = re.sub(
        r"[‐-‒–—−]",
        "-",
        text
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text.strip()


def verify_gold_evidence(row) -> bool:
    """
    Vérifie que le passage de référence existe réellement
    dans le document attendu.
    """

    expected_source = row[
        "expected_source_canonical"
    ]

    matching_documents = [
        doc
        for doc in documents
        if canonical_source(
            doc.metadata.get("source", "")
        ) == expected_source
    ]

    normalized_evidence = normalize_for_matching(
        row["gold_evidence"]
    )

    if not normalized_evidence:
        return False

    for doc in matching_documents:

        normalized_content = normalize_for_matching(
            doc.page_content
        )

        if normalized_evidence in normalized_content:
            return True

    return False


evaluation_df["evidence_exists"] = (
    evaluation_df.apply(
        verify_gold_evidence,
        axis=1
    )
)


evidence_validation_df = evaluation_df[
    [
        "id",
        "format",
        "source_exists",
        "evidence_exists"
    ]
]


display(evidence_validation_df)


invalid_questions_df = evaluation_df[
    (
        evaluation_df["source_exists"] == False
    )
    |
    (
        evaluation_df["evidence_exists"] == False
    )
]


print(
    "Questions invalides :",
    len(invalid_questions_df)
)

if not invalid_questions_df.empty:
    display(
        invalid_questions_df[
            [
                "id",
                "format",
                "expected_source",
                "source_exists",
                "evidence_exists",
                "gold_evidence"
            ]
        ]
    )

      id    format  source_exists  evidence_exists
0   Q001  markdown           True             True
1   Q002  markdown           True             True
2   Q003  markdown           True             True
3   Q004  markdown           True             True
4   Q005  markdown           True             True
5   Q006  markdown           True             True
6   Q007  markdown           True             True
7   Q008  markdown           True             True
8   Q009  markdown           True             True
9   Q010  markdown           True             True
10  Q011  markdown           True             True
11  Q012  markdown           True             True
12  Q013      html           True             True
13  Q014      html           True             True
14  Q015      html           True             True
15  Q016      html           True             True
16  Q017      html           True             True
17  Q018      html           True             True
18  Q019      html           True             True
19  Q020      html           True             True
20  Q021      html           True             True
21  Q022      html           True             True
22  Q023       pdf           True             True
23  Q024       pdf           True             True
24  Q025       pdf           True             True
25  Q026       pdf           True             True
26  Q027       pdf           True             True
27  Q028       pdf           True             True
28  Q029       pdf           True             True
29  Q030       pdf           True             True

Questions invalides : 0

**la validation obligatoire des 30 questions**

In [93]:
invalid_evidence_df = evaluation_df[
    evaluation_df["evidence_exists"] == False
][
    [
        "id",
        "format",
        "expected_source",
        "source_exists",
        "gold_evidence"
    ]
]

print(
    "Nombre de preuves introuvables :",
    len(invalid_evidence_df)
)

display(invalid_evidence_df)

Nombre de preuves introuvables : 0

Empty DataFrame
Columns: [id, format, expected_source, source_exists, gold_evidence]
Index: []

In [94]:
expected_configurations = {
    ("fixed", 256),
    ("fixed", 512),
    ("fixed", 1024),

    ("recursive", 256),
    ("recursive", 512),
    ("recursive", 1024),

    ("semantic", 85),
    ("semantic", 90),
    ("semantic", 95)
}


available_configurations = set(
    chunking_results.keys()
)


missing_configurations = (
    expected_configurations
    - available_configurations
)

unexpected_configurations = (
    available_configurations
    - expected_configurations
)


print(
    "Configurations disponibles :",
    len(available_configurations)
)

for key in sorted(
    available_configurations,
    key=lambda item: (
        str(item[0]),
        int(item[1])
    )
):
    print(
        f"{key!r:<30}",
        "→",
        len(chunking_results[key]),
        "chunks"
    )


print(
    "\nConfigurations manquantes :",
    missing_configurations
)

print(
    "Configurations inattendues :",
    unexpected_configurations
)


assert len(
    available_configurations
) == 9, (
    f"9 configurations attendues, "
    f"{len(available_configurations)} trouvées."
)

assert not missing_configurations, (
    f"Configurations manquantes : "
    f"{missing_configurations}"
)


print(
    "\n✅ Les 9 configurations sont prêtes"
)

Configurations disponibles : 9
('fixed', 256)                 → 5343 chunks
('fixed', 512)                 → 2751 chunks
('fixed', 1024)                → 1478 chunks
('recursive', 256)             → 5727 chunks
('recursive', 512)             → 2870 chunks
('recursive', 1024)            → 1483 chunks
('semantic', 85)               → 1917 chunks
('semantic', 90)               → 1585 chunks
('semantic', 95)               → 1309 chunks

Configurations manquantes : set()
Configurations inattendues : set()

✅ Les 9 configurations sont prêtes

In [95]:
format_counts = (
    evaluation_df["format"]
    .value_counts()
)


assert len(evaluation_df) == 30, (
    f"30 questions attendues, "
    f"{len(evaluation_df)} trouvées."
)

assert (
    format_counts.get("markdown", 0)
    == 12
), (
    "Il faut exactement 12 questions Markdown."
)

assert (
    format_counts.get("html", 0)
    == 10
), (
    "Il faut exactement 10 questions HTML."
)

assert (
    format_counts.get("pdf", 0)
    == 8
), (
    "Il faut exactement 8 questions PDF."
)

assert (
    evaluation_df["source_exists"].all()
), (
    "Certaines sources n'existent pas."
)

assert (
    evaluation_df["evidence_exists"].all()
), (
    "Certains passages de référence "
    "n'existent pas dans les documents."
)


evaluation_df.to_csv(
    evaluation_path,
    index=False,
    encoding="utf-8"
)


print(
    " Jeu d'évaluation validé : 30 questions"
)

print(
    "Fichier enregistré :",
    evaluation_path
)

 Jeu d'évaluation validé : 30 questions
Fichier enregistré : /content/evaluation/chunking_evaluation_30_questions.csv

In [96]:
def search_text_in_documents(
    keyword: str
) -> None:

    keyword_normalized = (
        normalize_for_matching(keyword)
    )

    for doc in documents:
        content_normalized = (
            normalize_for_matching(
                doc.page_content
            )
        )

        if keyword_normalized in content_normalized:
            print("\n" + "=" * 100)
            print(
                "Source :",
                doc.metadata.get("source")
            )
            print(
                "Page :",
                doc.metadata.get("page", "N/A")
            )
            print("-" * 100)

            position = content_normalized.find(
                keyword_normalized
            )

            start = max(
                0,
                position - 300
            )

            end = min(
                len(content_normalized),
                position + len(keyword_normalized) + 500
            )

            print(
                content_normalized[start:end]
            )

**Étape 7 — Vérifier les configurations présentes**

---

In [99]:
expected_configurations = {
    ("fixed", 256),
    ("fixed", 512),
    ("fixed", 1024),

    ("recursive", 256),
    ("recursive", 512),
    ("recursive", 1024),

    ("semantic", 85),
    ("semantic", 90),
    ("semantic", 95)
}


available_configurations = set(
    chunking_results.keys()
)


missing_configurations = (
    expected_configurations
    - available_configurations
)

unexpected_configurations = (
    available_configurations
    - expected_configurations
)


print(
    "Configurations disponibles :",
    len(available_configurations)
)

for key in sorted(
    available_configurations,
    key=lambda item: (
        str(item[0]),
        int(item[1])
    )
):
    print(
        f"{key!r:<30}",
        "→",
        len(chunking_results[key]),
        "chunks"
    )


print(
    "\nConfigurations manquantes :",
    missing_configurations
)

print(
    "Configurations inattendues :",
    unexpected_configurations
)


assert len(
    available_configurations
) == 9, (
    f"9 configurations attendues, "
    f"{len(available_configurations)} trouvées."
)

assert not missing_configurations, (
    f"Configurations manquantes : "
    f"{missing_configurations}"
)


print(
    "\n✅ Les 9 configurations sont prêtes"
)

Configurations disponibles : 9
('fixed', 256)                 → 5343 chunks
('fixed', 512)                 → 2751 chunks
('fixed', 1024)                → 1478 chunks
('recursive', 256)             → 5727 chunks
('recursive', 512)             → 2870 chunks
('recursive', 1024)            → 1483 chunks
('semantic', 85)               → 1917 chunks
('semantic', 90)               → 1585 chunks
('semantic', 95)               → 1309 chunks

Configurations manquantes : set()
Configurations inattendues : set()

✅ Les 9 configurations sont prêtes

In [98]:
from pathlib import Path

DATASET_PATH = Path("/content/benchmark_dataset")

print("Dataset présent :", DATASET_PATH.exists())
print(
    "Nombre de fichiers :",
    len([
        path
        for path in DATASET_PATH.rglob("*")
        if path.is_file()
    ])
)

Dataset présent : True
Nombre de fichiers : 19

**Étape 8 — Installer et importer FAISS**

In [100]:
!pip install -q faiss-cpu

In [101]:
import faiss
import numpy as np
import pandas as pd
import time

print("Version FAISS :", faiss.__version__)

Version FAISS : 1.14.3

**Étape 9 — Préparer les textes avant embedding**

**Étape 10 — Générer les embeddings des chunks**

**Étape 11 — Construire l’index FAISS**

**Étape 12 — Tester une première recherche**

**Étape 13 — Définir la pertinence d’un résultat**

*Pertinence au niveau de la source*

In [103]:
def is_source_relevant(
    result: dict,
    expected_source: str
) -> bool:
    """
    Vérifie si le résultat vient du document attendu,
    indépendamment du chemin Windows ou Linux.
    """

    retrieved_source = canonical_source(
        result.get("source", "")
    )

    expected_source_normalized = canonical_source(
        expected_source
    )

    return (
        retrieved_source
        == expected_source_normalized
    )

**Pertinence au niveau du passage de preuve**

In [104]:
import re
import unicodedata


def normalize_evaluation_text(
    text: str
) -> str:

    text = unicodedata.normalize(
        "NFKC",
        str(text)
    ).lower()

    text = re.sub(
        r"[^\w\s]",
        " ",
        text
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text.strip()

In [105]:
def evidence_token_recall(
    retrieved_text: str,
    gold_evidence: str
) -> float:
    """
    Proportion des mots distinctifs du passage de référence
    présents dans le chunk récupéré.
    """

    retrieved_tokens = set(
        normalize_evaluation_text(
            retrieved_text
        ).split()
    )

    evidence_tokens = set(
        normalize_evaluation_text(
            gold_evidence
        ).split()
    )

    if not evidence_tokens:
        return 0.0

    common_tokens = (
        retrieved_tokens
        & evidence_tokens
    )

    return (
        len(common_tokens)
        / len(evidence_tokens)
    )

In [106]:
EVIDENCE_THRESHOLD = 0.60


def is_evidence_relevant(
    result: dict,
    expected_source: str,
    gold_evidence: str,
    threshold: float = EVIDENCE_THRESHOLD
) -> bool:
    """
    Vérifie simultanément :
    1. que le résultat vient de la bonne source ;
    2. qu'il contient suffisamment du passage attendu.
    """

    if not is_source_relevant(
        result=result,
        expected_source=expected_source
    ):
        return False

    normalized_chunk = normalize_for_matching(
        result.get("text", "")
    )

    normalized_evidence = normalize_for_matching(
        gold_evidence
    )

    if not normalized_evidence:
        return False

    # Cas idéal : passage complet présent.
    if normalized_evidence in normalized_chunk:
        return True

    # Cas où une frontière de chunk coupe le passage.
    overlap_score = evidence_token_recall(
        retrieved_text=result.get(
            "text",
            ""
        ),
        gold_evidence=gold_evidence
    )

    return overlap_score >= threshold

**Étape 14 — Calculer Recall@K et MRR**

In [107]:
def reciprocal_rank(
    relevance_values: list[bool]
) -> float:

    for rank, relevant in enumerate(
        relevance_values,
        start=1
    ):
        if relevant:
            return 1.0 / rank

    return 0.0

In [111]:
import faiss
import numpy as np


def search_faiss(
    question: str,
    index,
    chunks,
    embeddings,
    top_k: int = 5
) -> list[dict]:
    """
    Encode une question, recherche les chunks les plus proches
    dans l'index FAISS et retourne les résultats classés.
    """

    if not question or not question.strip():
        raise ValueError(
            "La question ne peut pas être vide."
        )

    if top_k <= 0:
        raise ValueError(
            "top_k doit être strictement positif."
        )

    if index.ntotal != len(chunks):
        raise ValueError(
            "Le nombre de vecteurs FAISS ne correspond pas "
            "au nombre de chunks : "
            f"{index.ntotal} vecteurs contre {len(chunks)} chunks."
        )

    # Créer l'embedding de la question
    query_vector = embeddings.embed_query(
        question
    )

    query_vector = np.asarray(
        [query_vector],
        dtype=np.float32
    )

    if query_vector.ndim != 2:
        raise ValueError(
            "La forme du vecteur de requête est invalide."
        )

    # Sécurité : normalisation L2 pour IndexFlatIP
    faiss.normalize_L2(
        query_vector
    )

    effective_top_k = min(
        top_k,
        index.ntotal
    )

    scores, indices = index.search(
        query_vector,
        effective_top_k
    )

    results = []

    for rank, (
        chunk_index,
        score
    ) in enumerate(
        zip(indices[0], scores[0]),
        start=1
    ):
        if chunk_index < 0:
            continue

        chunk = chunks[
            int(chunk_index)
        ]

        results.append({
            "rank": rank,
            "score": float(score),
            "chunk_index": int(chunk_index),
            "chunk_id": chunk.metadata.get(
                "chunk_id"
            ),
            "source": chunk.metadata.get(
                "source"
            ),
            "text": chunk.page_content
        })

    return results


print(
    "✅ Fonction search_faiss définie"
)

✅ Fonction search_faiss définie

In [108]:
def evaluate_single_configuration(
    evaluation_data: pd.DataFrame,
    index,
    chunks: list[Document],
    embeddings,
    configuration_name: str,
    retrieval_k: int = 10,
    evidence_threshold: float = 0.60
):
    """
    Évalue une configuration avec :
    - Source Recall@1, @3, @5, @10
    - Evidence Recall@1, @3, @5, @10
    - Source MRR
    - Evidence MRR
    - latence moyenne
    """

    question_records = []

    for _, row in evaluation_data.iterrows():
        start_time = time.perf_counter()

        results = search_faiss(
            question=row["question"],
            index=index,
            chunks=chunks,
            embeddings=embeddings,
            top_k=retrieval_k
        )

        retrieval_time = (
            time.perf_counter() - start_time
        )

        source_relevance = [
            is_source_relevant(
                result=result,
                expected_source=row["expected_source"]
            )
            for result in results
        ]

        evidence_relevance = [
            is_evidence_relevant(
                result=result,
                expected_source=row["expected_source"],
                gold_evidence=row["gold_evidence"],
                threshold=evidence_threshold
            )
            for result in results
        ]

        record = {
            "configuration": configuration_name,
            "question_id": row["id"],
            "question": row["question"],
            "expected_source": row["expected_source"],
            "retrieval_time_seconds": retrieval_time,

            "source_recall_at_1":
                int(any(source_relevance[:1])),

            "source_recall_at_3":
                int(any(source_relevance[:3])),

            "source_recall_at_5":
                int(any(source_relevance[:5])),

            "source_recall_at_10":
                int(any(source_relevance[:10])),

            "evidence_recall_at_1":
                int(any(evidence_relevance[:1])),

            "evidence_recall_at_3":
                int(any(evidence_relevance[:3])),

            "evidence_recall_at_5":
                int(any(evidence_relevance[:5])),

            "evidence_recall_at_10":
                int(any(evidence_relevance[:10])),

            "source_reciprocal_rank":
                reciprocal_rank(source_relevance),

            "evidence_reciprocal_rank":
                reciprocal_rank(evidence_relevance),

            "top_1_source":
                results[0]["source"]
                if results else None,

            "top_1_score":
                results[0]["score"]
                if results else None
        }

        question_records.append(record)

    detail_df = pd.DataFrame(
        question_records
    )

    summary = {
        "configuration": configuration_name,
        "number_of_questions": len(detail_df),

        "source_recall_at_1":
            detail_df["source_recall_at_1"].mean(),

        "source_recall_at_3":
            detail_df["source_recall_at_3"].mean(),

        "source_recall_at_5":
            detail_df["source_recall_at_5"].mean(),

        "source_recall_at_10":
            detail_df["source_recall_at_10"].mean(),

        "evidence_recall_at_1":
            detail_df["evidence_recall_at_1"].mean(),

        "evidence_recall_at_3":
            detail_df["evidence_recall_at_3"].mean(),

        "evidence_recall_at_5":
            detail_df["evidence_recall_at_5"].mean(),

        "evidence_recall_at_10":
            detail_df["evidence_recall_at_10"].mean(),

        "source_mrr":
            detail_df[
                "source_reciprocal_rank"
            ].mean(),

        "evidence_mrr":
            detail_df[
                "evidence_reciprocal_rank"
            ].mean(),

        "mean_retrieval_time_ms":
            detail_df[
                "retrieval_time_seconds"
            ].mean() * 1000,

        "p95_retrieval_time_ms":
            detail_df[
                "retrieval_time_seconds"
            ].quantile(0.95) * 1000
    }

    summary_df = pd.DataFrame(
        [summary]
    )

    return summary_df, detail_df

In [112]:
required_functions = [
    "search_faiss",
    "evaluate_single_configuration",
    "is_source_relevant",
    "is_evidence_relevant",
    "evidence_token_recall",
    "reciprocal_rank",
    "canonical_source",
    "detect_format"
]

missing_functions = [
    function_name
    for function_name in required_functions
    if function_name not in globals()
]

print(
    "Fonctions manquantes :",
    missing_functions
)

assert not missing_functions, (
    "Exécute les cellules qui définissent : "
    + ", ".join(missing_functions)
)

print(
    "✅ Toutes les fonctions du benchmark sont chargées"
)

Fonctions manquantes : []
✅ Toutes les fonctions du benchmark sont chargées

**Étape 15 — Évaluer Recursive 512**

**Étape 16 — Identifier les questions échouées**

**Étape 17 — Boucle automatique sur les 9 configurations**

In [114]:
required_objects = [
    "evaluation_df",
    "chunking_results",
    "embedding_model",
    "EMBEDDING_MODEL_NAME",
    "search_faiss",
    "evaluate_single_configuration",
    "detect_format"
]


missing_objects = [
    object_name
    for object_name in required_objects
    if object_name not in globals()
]


print(
    "Objets manquants :",
    missing_objects
)


assert not missing_objects, (
    "Les objets suivants sont manquants : "
    + ", ".join(missing_objects)
)


print(
    "✅ Le benchmark peut être lancé"
)

Objets manquants : []
✅ Le benchmark peut être lancé

In [115]:
import gc
import json
import time
from pathlib import Path

import faiss
import numpy as np
import pandas as pd


# ============================================================
# 1. Dossiers
# ============================================================

EMBEDDING_CACHE_DIR = Path(
    "/content/embedding_cache"
)

EMBEDDING_CACHE_DIR.mkdir(
    parents=True,
    exist_ok=True
)


RESULTS_DIR = Path(
    "/content/chunking_benchmark_results"
)

RESULTS_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# 2. Paramètres
# ============================================================

TOP_K = 10
EVIDENCE_THRESHOLD = 0.60


# ============================================================
# 3. Contrôles avant exécution
# ============================================================

assert len(evaluation_df) == 30, (
    f"Le benchmark nécessite 30 questions, "
    f"mais {len(evaluation_df)} ont été trouvées."
)

assert evaluation_df["source_exists"].all(), (
    "Certaines sources sont invalides."
)

assert evaluation_df["evidence_exists"].all(), (
    "Certaines preuves sont invalides."
)

assert len(chunking_results) == 9, (
    f"Le benchmark nécessite 9 configurations, "
    f"mais {len(chunking_results)} ont été trouvées."
)

assert "search_faiss" in globals(), (
    "La fonction search_faiss n'est pas définie."
)

assert "evaluate_single_configuration" in globals(), (
    "La fonction evaluate_single_configuration "
    "n'est pas définie."
)

assert "EMBEDDING_MODEL_NAME" in globals(), (
    "La variable EMBEDDING_MODEL_NAME "
    "n'est pas définie."
)


# ============================================================
# 4. Préparation
# ============================================================

all_summary_results = []
all_detail_results = []

benchmark_start_time = time.perf_counter()


configuration_items = sorted(
    chunking_results.items(),
    key=lambda item: (
        str(item[0][0]),
        int(item[0][1])
    )
)


number_of_configurations = len(
    configuration_items
)


print(
    "Configurations à tester :",
    number_of_configurations
)

print(
    "Questions par configuration :",
    len(evaluation_df)
)

print(
    "Nombre total de recherches :",
    number_of_configurations
    * len(evaluation_df)
)


# ============================================================
# 5. Boucle des 9 configurations
# ============================================================

for configuration_number, (
    configuration_key,
    chunks
) in enumerate(
    configuration_items,
    start=1
):

    strategy = str(
        configuration_key[0]
    )

    parameter = int(
        configuration_key[1]
    )

    configuration_name = (
        f"{strategy}_{parameter}"
    )


    print("\n" + "=" * 100)

    print(
        f"Configuration "
        f"{configuration_number}/"
        f"{number_of_configurations} : "
        f"{configuration_name}"
    )

    print(
        "Nombre de chunks :",
        len(chunks)
    )

    print("=" * 100)


    configuration_start_time = (
        time.perf_counter()
    )


    # --------------------------------------------------------
    # A. Préparer les textes
    # --------------------------------------------------------

    chunk_texts = [
        chunk.page_content.strip()
        for chunk in chunks
    ]


    empty_chunk_count = sum(
        1
        for text in chunk_texts
        if not text
    )


    if empty_chunk_count > 0:
        raise ValueError(
            f"{configuration_name} contient "
            f"{empty_chunk_count} chunks vides."
        )


    print("Chunks vides : 0")


    # --------------------------------------------------------
    # B. Construire les chemins du cache
    # --------------------------------------------------------

    safe_model_name = (
        EMBEDDING_MODEL_NAME
        .replace("/", "__")
        .replace("\\", "__")
    )


    embedding_cache_path = (
        EMBEDDING_CACHE_DIR
        / (
            f"{configuration_name}"
            f"__{safe_model_name}.npy"
        )
    )


    metadata_cache_path = (
        EMBEDDING_CACHE_DIR
        / (
            f"{configuration_name}"
            f"__{safe_model_name}.json"
        )
    )


    embedding_loaded_from_cache = False


    # --------------------------------------------------------
    # C. Charger ou générer les embeddings
    # --------------------------------------------------------

    embedding_start_time = (
        time.perf_counter()
    )


    if embedding_cache_path.exists():

        print(
            "Cache trouvé :",
            embedding_cache_path.name
        )


        chunk_vectors = np.load(
            embedding_cache_path,
            allow_pickle=False
        ).astype(
            np.float32,
            copy=False
        )


        embedding_loaded_from_cache = True


        embedding_time_seconds = (
            time.perf_counter()
            - embedding_start_time
        )


    else:

        print(
            "Cache absent : calcul des embeddings"
        )


        chunk_vectors = (
            embedding_model.embed_documents(
                chunk_texts
            )
        )


        chunk_vectors = np.asarray(
            chunk_vectors,
            dtype=np.float32
        )


        if chunk_vectors.ndim != 2:
            raise ValueError(
                f"Embeddings invalides pour "
                f"{configuration_name} : "
                f"{chunk_vectors.shape}"
            )


        # Normalisation avant sauvegarde
        faiss.normalize_L2(
            chunk_vectors
        )


        embedding_time_seconds = (
            time.perf_counter()
            - embedding_start_time
        )


        np.save(
            embedding_cache_path,
            chunk_vectors
        )


        cache_metadata = {
            "configuration": configuration_name,
            "strategy": strategy,
            "parameter": parameter,
            "model_name": EMBEDDING_MODEL_NAME,
            "number_of_chunks": len(chunks),
            "embedding_dimension": int(
                chunk_vectors.shape[1]
            ),
            "normalized": True,
            "embedding_time_seconds": float(
                embedding_time_seconds
            )
        }


        with open(
            metadata_cache_path,
            "w",
            encoding="utf-8"
        ) as metadata_file:

            json.dump(
                cache_metadata,
                metadata_file,
                indent=4,
                ensure_ascii=False
            )


        print(
            "Cache enregistré :",
            embedding_cache_path.name
        )


    # --------------------------------------------------------
    # D. Vérifier le cache ou les embeddings calculés
    # --------------------------------------------------------

    if chunk_vectors.ndim != 2:
        raise ValueError(
            f"Embeddings invalides pour "
            f"{configuration_name} : "
            f"{chunk_vectors.shape}"
        )


    if chunk_vectors.shape[0] != len(chunks):
        raise ValueError(
            f"Cache incompatible pour "
            f"{configuration_name} : "
            f"{chunk_vectors.shape[0]} vecteurs "
            f"pour {len(chunks)} chunks."
        )


    embedding_dimension = int(
        chunk_vectors.shape[1]
    )


    print(
        "Forme des embeddings :",
        chunk_vectors.shape
    )

    print(
        "Chargés depuis le cache :",
        embedding_loaded_from_cache
    )

    print(
        "Temps chargement/calcul :",
        round(
            embedding_time_seconds,
            3
        ),
        "secondes"
    )


    # --------------------------------------------------------
    # E. Vérifier puis normaliser les vecteurs
    # --------------------------------------------------------

    vector_norms_before = np.linalg.norm(
        chunk_vectors,
        axis=1
    )


    mean_vector_norm = float(
        vector_norms_before.mean()
    )


    print(
        "Norme moyenne avant FAISS :",
        round(
            mean_vector_norm,
            4
        )
    )


    # Sécurité supplémentaire
    faiss.normalize_L2(
        chunk_vectors
    )


    # --------------------------------------------------------
    # F. Construire l'index FAISS
    # --------------------------------------------------------

    faiss_index = faiss.IndexFlatIP(
        embedding_dimension
    )


    indexing_start_time = (
        time.perf_counter()
    )


    faiss_index.add(
        chunk_vectors
    )


    faiss_indexing_time_seconds = (
        time.perf_counter()
        - indexing_start_time
    )


    print(
        "Vecteurs indexés :",
        faiss_index.ntotal
    )

    print(
        "Temps d'indexation FAISS :",
        round(
            faiss_indexing_time_seconds,
            4
        ),
        "secondes"
    )


    # --------------------------------------------------------
    # G. Évaluer les 30 questions
    # --------------------------------------------------------

    summary_df, details_df = (
        evaluate_single_configuration(
            evaluation_data=evaluation_df,
            index=faiss_index,
            chunks=chunks,
            embeddings=embedding_model,
            configuration_name=configuration_name,
            retrieval_k=TOP_K,
            evidence_threshold=EVIDENCE_THRESHOLD
        )
    )


    total_configuration_time_seconds = (
        time.perf_counter()
        - configuration_start_time
    )


    # --------------------------------------------------------
    # H. Ajouter les informations techniques
    # --------------------------------------------------------

    summary_df["strategy"] = strategy

    summary_df["parameter"] = parameter


    summary_df[
        "number_of_chunks"
    ] = len(chunks)


    summary_df[
        "embedding_model"
    ] = EMBEDDING_MODEL_NAME


    summary_df[
        "embedding_dimension"
    ] = embedding_dimension


    summary_df[
        "embedding_time_seconds"
    ] = embedding_time_seconds


    summary_df[
        "embedding_loaded_from_cache"
    ] = embedding_loaded_from_cache


    summary_df[
        "embedding_cache_path"
    ] = str(
        embedding_cache_path
    )


    summary_df[
        "metadata_cache_path"
    ] = str(
        metadata_cache_path
    )


    summary_df[
        "faiss_indexing_time_seconds"
    ] = faiss_indexing_time_seconds


    summary_df[
        "total_configuration_time_seconds"
    ] = total_configuration_time_seconds


    summary_df[
        "mean_vector_norm"
    ] = mean_vector_norm


    summary_df[
        "questions_markdown"
    ] = int(
        (
            evaluation_df["format"]
            == "markdown"
        ).sum()
    )


    summary_df[
        "questions_html"
    ] = int(
        (
            evaluation_df["format"]
            == "html"
        ).sum()
    )


    summary_df[
        "questions_pdf"
    ] = int(
        (
            evaluation_df["format"]
            == "pdf"
        ).sum()
    )


    details_df["format"] = (
        details_df["expected_source"]
        .apply(detect_format)
    )


    details_df[
        "embedding_model"
    ] = EMBEDDING_MODEL_NAME


    details_df[
        "embedding_loaded_from_cache"
    ] = embedding_loaded_from_cache


    # --------------------------------------------------------
    # I. Stocker les résultats
    # --------------------------------------------------------

    all_summary_results.append(
        summary_df.copy()
    )


    all_detail_results.append(
        details_df.copy()
    )


    print("\nRésultats :")


    print(
        "Evidence Recall@1 :",
        round(
            summary_df[
                "evidence_recall_at_1"
            ].iloc[0],
            4
        )
    )


    print(
        "Evidence Recall@3 :",
        round(
            summary_df[
                "evidence_recall_at_3"
            ].iloc[0],
            4
        )
    )


    print(
        "Evidence Recall@5 :",
        round(
            summary_df[
                "evidence_recall_at_5"
            ].iloc[0],
            4
        )
    )


    print(
        "Evidence MRR :",
        round(
            summary_df[
                "evidence_mrr"
            ].iloc[0],
            4
        )
    )


    print(
        "Temps total :",
        round(
            total_configuration_time_seconds,
            2
        ),
        "secondes"
    )


    # --------------------------------------------------------
    # J. Sauvegarde intermédiaire
    # --------------------------------------------------------

    progress_summary_df = pd.concat(
        all_summary_results,
        ignore_index=True
    )


    progress_details_df = pd.concat(
        all_detail_results,
        ignore_index=True
    )


    progress_summary_df.to_csv(
        RESULTS_DIR
        / "chunking_summary_progress.csv",
        index=False,
        encoding="utf-8"
    )


    progress_details_df.to_csv(
        RESULTS_DIR
        / "chunking_details_progress.csv",
        index=False,
        encoding="utf-8"
    )


    print(
        "Progression sauvegardée :",
        configuration_name
    )


    # --------------------------------------------------------
    # K. Libérer la mémoire
    # --------------------------------------------------------

    del chunk_texts
    del chunk_vectors
    del faiss_index
    del summary_df
    del details_df
    del progress_summary_df
    del progress_details_df


    gc.collect()


# ============================================================
# 6. Fin du benchmark
# ============================================================

benchmark_total_time_seconds = (
    time.perf_counter()
    - benchmark_start_time
)


print("\n" + "=" * 100)

print(
    "✅ BENCHMARK DES 9 CONFIGURATIONS TERMINÉ"
)

print(
    "Temps total :",
    round(
        benchmark_total_time_seconds / 60,
        2
    ),
    "minutes"
)

print("=" * 100)

Configurations à tester : 9
Questions par configuration : 30
Nombre total de recherches : 270

====================================================================================================
Configuration 1/9 : fixed_256
Nombre de chunks : 5343
====================================================================================================
Chunks vides : 0
Cache absent : calcul des embeddings
Cache enregistré : fixed_256__BAAI__bge-small-en-v1.5.npy
Forme des embeddings : (5343, 384)
Chargés depuis le cache : False
Temps chargement/calcul : 689.299 secondes
Norme moyenne avant FAISS : 1.0
Vecteurs indexés : 5343
Temps d'indexation FAISS : 0.0028 secondes

Résultats :
Evidence Recall@1 : 0.4
Evidence Recall@3 : 0.6667
Evidence Recall@5 : 0.6667
Evidence MRR : 0.5349
Temps total : 690.81 secondes
Progression sauvegardée : fixed_256

====================================================================================================
Configuration 2/9 : fixed_512
Nombre de chunks : 2751
====================================================================================================
Chunks vides : 0
Cache absent : calcul des embeddings
Cache enregistré : fixed_512__BAAI__bge-small-en-v1.5.npy
Forme des embeddings : (2751, 384)
Chargés depuis le cache : False
Temps chargement/calcul : 712.019 secondes
Norme moyenne avant FAISS : 1.0
Vecteurs indexés : 2751
Temps d'indexation FAISS : 0.0011 secondes

Résultats :
Evidence Recall@1 : 0.5
Evidence Recall@3 : 0.7333
Evidence Recall@5 : 0.8333
Evidence MRR : 0.6414
Temps total : 713.23 secondes
Progression sauvegardée : fixed_512

====================================================================================================
Configuration 3/9 : fixed_1024
Nombre de chunks : 1478
====================================================================================================
Chunks vides : 0
Cache absent : calcul des embeddings
Cache enregistré : fixed_1024__BAAI__bge-small-en-v1.5.npy
Forme des embeddings : (1478, 384)
Chargés depuis le cache : False
Temps chargement/calcul : 656.038 secondes
Norme moyenne avant FAISS : 1.0
Vecteurs indexés : 1478
Temps d'indexation FAISS : 0.0006 secondes

Résultats :
Evidence Recall@1 : 0.5667
Evidence Recall@3 : 0.8667
Evidence Recall@5 : 1.0
Evidence MRR : 0.7378
Temps total : 657.25 secondes
Progression sauvegardée : fixed_1024

====================================================================================================
Configuration 4/9 : recursive_256
Nombre de chunks : 5727
====================================================================================================
Chunks vides : 0
Cache absent : calcul des embeddings
Cache enregistré : recursive_256__BAAI__bge-small-en-v1.5.npy
Forme des embeddings : (5727, 384)
Chargés depuis le cache : False
Temps chargement/calcul : 803.131 secondes
Norme moyenne avant FAISS : 1.0
Vecteurs indexés : 5727
Temps d'indexation FAISS : 0.0022 secondes

Résultats :
Evidence Recall@1 : 0.3667
Evidence Recall@3 : 0.6333
Evidence Recall@5 : 0.7333
Evidence MRR : 0.5209
Temps total : 804.41 secondes
Progression sauvegardée : recursive_256

====================================================================================================
Configuration 5/9 : recursive_512
Nombre de chunks : 2870
====================================================================================================
Chunks vides : 0
Cache absent : calcul des embeddings
Cache enregistré : recursive_512__BAAI__bge-small-en-v1.5.npy
Forme des embeddings : (2870, 384)
Chargés depuis le cache : False
Temps chargement/calcul : 1061.174 secondes
Norme moyenne avant FAISS : 1.0
Vecteurs indexés : 2870
Temps d'indexation FAISS : 0.0015 secondes

Résultats :
Evidence Recall@1 : 0.5667
Evidence Recall@3 : 0.8333
Evidence Recall@5 : 0.9333
Evidence MRR : 0.705
Temps total : 1062.52 secondes
Progression sauvegardée : recursive_512

====================================================================================================
Configuration 6/9 : recursive_1024
Nombre de chunks : 1483
====================================================================================================
Chunks vides : 0
Cache absent : calcul des embeddings
Cache enregistré : recursive_1024__BAAI__bge-small-en-v1.5.npy
Forme des embeddings : (1483, 384)
Chargés depuis le cache : False
Temps chargement/calcul : 863.03 secondes
Norme moyenne avant FAISS : 1.0
Vecteurs indexés : 1483
Temps d'indexation FAISS : 0.0008 secondes

Résultats :
Evidence Recall@1 : 0.6667
Evidence Recall@3 : 0.8667
Evidence Recall@5 : 0.9333
Evidence MRR : 0.7887
Temps total : 864.27 secondes
Progression sauvegardée : recursive_1024

====================================================================================================
Configuration 7/9 : semantic_85
Nombre de chunks : 1917
====================================================================================================
Chunks vides : 0
Cache absent : calcul des embeddings
Cache enregistré : semantic_85__BAAI__bge-small-en-v1.5.npy
Forme des embeddings : (1917, 384)
Chargés depuis le cache : False
Temps chargement/calcul : 774.524 secondes
Norme moyenne avant FAISS : 1.0
Vecteurs indexés : 1917
Temps d'indexation FAISS : 0.0007 secondes

Résultats :
Evidence Recall@1 : 0.5667
Evidence Recall@3 : 0.7667
Evidence Recall@5 : 0.8333
Evidence MRR : 0.6842
Temps total : 775.73 secondes
Progression sauvegardée : semantic_85

====================================================================================================
Configuration 8/9 : semantic_90
Nombre de chunks : 1585
====================================================================================================
Chunks vides : 0
Cache absent : calcul des embeddings
Cache enregistré : semantic_90__BAAI__bge-small-en-v1.5.npy
Forme des embeddings : (1585, 384)
Chargés depuis le cache : False
Temps chargement/calcul : 642.114 secondes
Norme moyenne avant FAISS : 1.0
Vecteurs indexés : 1585
Temps d'indexation FAISS : 0.0006 secondes

Résultats :
Evidence Recall@1 : 0.5
Evidence Recall@3 : 0.8667
Evidence Recall@5 : 0.9
Evidence MRR : 0.672
Temps total : 643.34 secondes
Progression sauvegardée : semantic_90

====================================================================================================
Configuration 9/9 : semantic_95
Nombre de chunks : 1309
====================================================================================================
Chunks vides : 0
Cache absent : calcul des embeddings
Cache enregistré : semantic_95__BAAI__bge-small-en-v1.5.npy
Forme des embeddings : (1309, 384)
Chargés depuis le cache : False
Temps chargement/calcul : 501.22 secondes
Norme moyenne avant FAISS : 1.0
Vecteurs indexés : 1309
Temps d'indexation FAISS : 0.0006 secondes

Résultats :
Evidence Recall@1 : 0.6
Evidence Recall@3 : 0.8333
Evidence Recall@5 : 0.9
Evidence MRR : 0.7346
Temps total : 502.84 secondes
Progression sauvegardée : semantic_95

====================================================================================================
✅ BENCHMARK DES 9 CONFIGURATIONS TERMINÉ
Temps total : 112.01 minutes
====================================================================================================

In [110]:
from pathlib import Path
import json
import numpy as np

EMBEDDING_CACHE_DIR = Path(
    "/content/embedding_cache"
)

EMBEDDING_CACHE_DIR.mkdir(
    parents=True,
    exist_ok=True
)

current_cache_path = (
    EMBEDDING_CACHE_DIR
    / "fixed_256__bge-small-en-v1.5.npy"
)

current_metadata_path = (
    EMBEDDING_CACHE_DIR
    / "fixed_256__bge-small-en-v1.5.json"
)

print(
    "chunk_vectors existe :",
    "chunk_vectors" in globals()
)

if "chunk_vectors" not in globals():
    raise RuntimeError(
        "chunk_vectors n'est plus présent en mémoire. "
        "Il faudra recalculer fixed_256."
    )

np.save(
    current_cache_path,
    np.asarray(
        chunk_vectors,
        dtype=np.float32
    )
)

current_metadata = {
    "configuration": "fixed_256",
    "model_name": EMBEDDING_MODEL_NAME,
    "number_of_chunks": len(
        chunking_results[
            ("fixed", 256)
        ]
    ),
    "embedding_dimension": int(
        chunk_vectors.shape[1]
    ),
    "normalized": True,
    "embedding_time_seconds": 731.693
}

with open(
    current_metadata_path,
    "w",
    encoding="utf-8"
) as file:
    json.dump(
        current_metadata,
        file,
        indent=4,
        ensure_ascii=False
    )

print(
    "✅ Embeddings fixed_256 sauvegardés :",
    current_cache_path
)

print(
    "Taille :",
    current_cache_path.stat().st_size
    / (1024 ** 2),
    "Mo"
)

chunk_vectors existe : True
✅ Embeddings fixed_256 sauvegardés : /content/embedding_cache/fixed_256__bge-small-en-v1.5.npy
Taille : 7.8267822265625 Mo

In [113]:
print(
    "faiss_index existe :",
    "faiss_index" in globals()
)

print(
    "Nombre de vecteurs :",
    faiss_index.ntotal
)

test_results = search_faiss(
    question=(
        "Who shares responsibility for "
        "cloud workload sustainability?"
    ),
    index=faiss_index,
    chunks=chunking_results[
        ("fixed", 256)
    ],
    embeddings=embedding_model,
    top_k=5
)

for result in test_results:
    print("\nRang :", result["rank"])
    print("Score :", round(result["score"], 4))
    print("Source :", result["source"])
    print(
        "Texte :",
        result["text"][:300]
    )

faiss_index existe : True
Nombre de vecteurs : 5343

Rang : 1
Score : 0.8383
Source : well-architected__sustainability__overview.md
Texte : rge, and how to reduce waste without compromising system quality.

What is a sustainable workload?

Sustainability has become a critical cloud architecture concern as hyperscale datacenters continue to expand, AI workloads drive unprecedented energy demand

Rang : 2
Score : 0.8365
Source : well-architected__sustainability__overview.md
Texte : Sustainable workloads on Azure

Sustainability for workloads in the cloud is a shared responsibility between the cloud provider and the organization. Azure workloads are carbon neutral and use 100% renewable energy. Microsoft also protects more land. By ru

Rang : 3
Score : 0.8004
Source : well-architected__sustainability__overview.md
Texte : dle virtual machines, oversized Kubernetes clusters, excessive telemetry, and unnecessary data replication all consume energy without delivering meaningful business value.

A sustainable workload is designed to minimize unnecessary resource consumption whi

Rang : 4
Score : 0.7947
Source : well-architected__sustainability__overview.md
Texte : s like cost, reliability, and performance. While many sustainability improvements align with cloud efficiency, they also require organizations to rethink how applications are designed, operated, and measured.

Challenge and description

Sustainability impa

Rang : 5
Score : 0.7766
Source : well-architected__sustainability__overview.md
Texte : ists between sustainability and Cost Optimization. Right-sizing infrastructure, autoscaling workloads, eliminating idle resources, and reducing unnecessary storage or network usage all improve cloud efficiency while also lowering environmental impact. Remo

**la fusion des résultats**

In [116]:
chunking_benchmark_summary_df = pd.concat(
    all_summary_results,
    ignore_index=True
)

chunking_benchmark_details_df = pd.concat(
    all_detail_results,
    ignore_index=True
)


print(
    "Configurations évaluées :",
    len(chunking_benchmark_summary_df)
)

print(
    "Lignes détaillées :",
    len(chunking_benchmark_details_df)
)


assert (
    len(chunking_benchmark_summary_df)
    == 9
), (
    "Le résumé doit contenir 9 lignes."
)

assert (
    len(chunking_benchmark_details_df)
    == 9 * 30
), (
    "Les détails doivent contenir "
    "9 × 30 = 270 lignes."
)


print(
    " Résultats complets : "
    "9 configurations et 270 évaluations"
)

Configurations évaluées : 9
Lignes détaillées : 270
 Résultats complets : 9 configurations et 270 évaluations

**Ajouter les résultats par format**

In [117]:
performance_by_format_df = (
    chunking_benchmark_details_df
    .groupby(
        [
            "configuration",
            "format"
        ],
        as_index=False
    )
    .agg(
        number_of_questions=(
            "question_id",
            "count"
        ),

        evidence_recall_at_1=(
            "evidence_recall_at_1",
            "mean"
        ),

        evidence_recall_at_3=(
            "evidence_recall_at_3",
            "mean"
        ),

        evidence_recall_at_5=(
            "evidence_recall_at_5",
            "mean"
        ),

        evidence_recall_at_10=(
            "evidence_recall_at_10",
            "mean"
        ),

        evidence_mrr=(
            "evidence_reciprocal_rank",
            "mean"
        ),

        source_recall_at_5=(
            "source_recall_at_5",
            "mean"
        ),

        mean_retrieval_time_ms=(
            "retrieval_time_seconds",
            lambda values:
                values.mean() * 1000
        )
    )
)


display(
    performance_by_format_df.round(4)
)

,configuration,format,number_of_questions,evidence_recall_at_1,evidence_recall_at_3,evidence_recall_at_5,evidence_recall_at_10,evidence_mrr,source_recall_at_5,mean_retrieval_time_ms
0,fixed_1024,html,10,0.7000,0.9000,1.0000,1.0000,0.8200,1.0,37.4747
1,fixed_1024,markdown,12,0.4167,0.9167,1.0000,1.0000,0.6694,1.0,38.9242
2,fixed_1024,pdf,8,0.6250,0.7500,1.0000,1.0000,0.7375,1.0,38.0326
3,fixed_256,html,10,0.7000,0.8000,0.8000,0.9000,0.7500,1.0,40.0142
4,fixed_256,markdown,12,0.2500,0.6667,0.6667,0.7500,0.4425,1.0,60.5669
5,fixed_256,pdf,8,0.2500,0.5000,0.5000,0.8750,0.4045,1.0,37.8295
6,fixed_512,html,10,0.6000,0.9000,0.9000,0.9000,0.7500,1.0,39.6245
7,fixed_512,markdown,12,0.5000,0.6667,0.8333,0.9167,0.6286,1.0,38.3526
8,fixed_512,pdf,8,0.3750,0.6250,0.7500,0.7500,0.5250,1.0,36.9668
9,recursive_1024,html,10,0.8000,0.9000,0.9000,1.0000,0.8611,1.0,38.0386
10,recursive_1024,markdown,12,0.5833,0.9167,1.0000,1.0000,0.7667,1.0,40.0701
11,recursive_1024,pdf,8,0.6250,0.7500,0.8750,1.0000,0.7312,1.0,37.9156
12,recursive_256,html,10,0.1000,0.7000,0.7000,0.8000,0.4143,1.0,38.7642
13,recursive_256,markdown,12,0.5000,0.5833,0.7500,0.7500,0.5611,1.0,40.1868
14,recursive_256,pdf,8,0.5000,0.6250,0.7500,0.7500,0.5938,1.0,43.7784
15,recursive_512,html,10,0.8000,0.9000,0.9000,0.9000,0.8500,1.0,39.0498
16,recursive_512,markdown,12,0.3333,0.7500,0.9167,0.9167,0.5514,1.0,42.0673
17,recursive_512,pdf,8,0.6250,0.8750,1.0000,1.0000,0.7542,1.0,45.1061
18,semantic_85,html,10,0.7000,0.8000,0.8000,1.0000,0.7768,1.0,36.7439
19,semantic_85,markdown,12,0.5000,0.6667,0.8333,0.9167,0.6208,1.0,39.1114
20,semantic_85,pdf,8,0.5000,0.8750,0.8750,1.0000,0.6637,1.0,36.7535
21,semantic_90,html,10,0.6000,0.9000,0.9000,1.0000,0.7267,1.0,37.3796
22,semantic_90,markdown,12,0.5833,0.9167,0.9167,0.9167,0.7222,1.0,39.3717
23,semantic_90,pdf,8,0.2500,0.7500,0.8750,1.0000,0.5283,1.0,37.0777
24,semantic_95,html,10,0.6000,0.8000,0.8000,1.0000,0.7310,1.0,41.5902
25,semantic_95,markdown,12,0.6667,0.9167,0.9167,1.0000,0.8009,1.0,61.7988
26,semantic_95,pdf,8,0.5000,0.7500,1.0000,1.0000,0.6396,1.0,40.8116

**le tableau comparatif final**

In [118]:
comparison_columns = [
    "configuration",
    "strategy",
    "parameter",
    "number_of_chunks",

    "evidence_recall_at_1",
    "evidence_recall_at_3",
    "evidence_recall_at_5",
    "evidence_recall_at_10",
    "evidence_mrr",

    "source_recall_at_1",
    "source_recall_at_3",
    "source_recall_at_5",
    "source_recall_at_10",
    "source_mrr",

    "mean_retrieval_time_ms",
    "p95_retrieval_time_ms",

    "embedding_time_seconds",
    "faiss_indexing_time_seconds",
    "total_configuration_time_seconds"
]


chunking_comparison_df = (
    chunking_benchmark_summary_df[
        comparison_columns
    ]
    .sort_values(
        by=[
            "evidence_recall_at_5",
            "evidence_mrr",
            "embedding_time_seconds"
        ],
        ascending=[
            False,
            False,
            True
        ]
    )
    .reset_index(
        drop=True
    )
)


display(
    chunking_comparison_df.round(4)
)

,configuration,strategy,parameter,number_of_chunks,evidence_recall_at_1,evidence_recall_at_3,evidence_recall_at_5,evidence_recall_at_10,evidence_mrr,source_recall_at_1,source_recall_at_3,source_recall_at_5,source_recall_at_10,source_mrr,mean_retrieval_time_ms,p95_retrieval_time_ms,embedding_time_seconds,faiss_indexing_time_seconds,total_configuration_time_seconds
0,fixed_1024,fixed,1024,1478,0.5667,0.8667,1.0000,1.0000,0.7378,0.9333,1.0000,1.0,1.0,0.9667,38.2033,43.7347,656.0378,0.0006,657.2547
1,recursive_1024,recursive,1024,1483,0.6667,0.8667,0.9333,1.0000,0.7887,0.9333,1.0000,1.0,1.0,0.9667,38.8184,43.8783,863.0304,0.0008,864.2678
2,recursive_512,recursive,512,2870,0.5667,0.8333,0.9333,0.9333,0.7050,0.8333,1.0000,1.0,1.0,0.9167,41.8718,58.2322,1061.1743,0.0015,1062.5179
3,semantic_95,semantic,95,1309,0.6000,0.8333,0.9000,1.0000,0.7346,0.8667,1.0000,1.0,1.0,0.9278,49.4660,68.3073,501.2204,0.0006,502.8420
4,semantic_90,semantic,90,1585,0.5000,0.8667,0.9000,0.9667,0.6720,0.8333,0.9667,1.0,1.0,0.9028,38.0959,43.5893,642.1137,0.0006,643.3353
5,semantic_85,semantic,85,1917,0.5667,0.7667,0.8333,0.9667,0.6842,0.9000,0.9667,1.0,1.0,0.9361,37.6934,42.7594,774.5238,0.0007,775.7266
6,fixed_512,fixed,512,2751,0.5000,0.7333,0.8333,0.8667,0.6414,0.9333,1.0000,1.0,1.0,0.9667,38.4070,43.3616,712.0195,0.0011,713.2318
7,recursive_256,recursive,256,5727,0.3667,0.6333,0.7333,0.7667,0.5209,0.9000,1.0000,1.0,1.0,0.9500,40.6703,52.4982,803.1311,0.0022,804.4074
8,fixed_256,fixed,256,5343,0.4000,0.6667,0.6667,0.8333,0.5349,0.9667,1.0000,1.0,1.0,0.9778,47.6527,67.9804,689.2993,0.0028,690.8147

**Sauvegarder les résultats**

In [119]:
summary_path = (
    RESULTS_DIR
    / "chunking_benchmark_summary_30_questions.csv"
)

details_path = (
    RESULTS_DIR
    / "chunking_benchmark_details_30_questions.csv"
)

format_path = (
    RESULTS_DIR
    / "chunking_benchmark_by_format_30_questions.csv"
)

comparison_path = (
    RESULTS_DIR
    / "chunking_benchmark_final_comparison_30_questions.csv"
)


chunking_benchmark_summary_df.to_csv(
    summary_path,
    index=False,
    encoding="utf-8"
)

chunking_benchmark_details_df.to_csv(
    details_path,
    index=False,
    encoding="utf-8"
)

performance_by_format_df.to_csv(
    format_path,
    index=False,
    encoding="utf-8"
)

chunking_comparison_df.to_csv(
    comparison_path,
    index=False,
    encoding="utf-8"
)


print("Résumé :", summary_path)
print("Détails :", details_path)
print("Par format :", format_path)
print("Comparaison :", comparison_path)

Résumé : /content/chunking_benchmark_results/chunking_benchmark_summary_30_questions.csv
Détails : /content/chunking_benchmark_results/chunking_benchmark_details_30_questions.csv
Par format : /content/chunking_benchmark_results/chunking_benchmark_by_format_30_questions.csv
Comparaison : /content/chunking_benchmark_results/chunking_benchmark_final_comparison_30_questions.csv

**la meilleure configuration**

In [120]:
best_configuration = (
    chunking_comparison_df.iloc[0]
)


print(
    "Meilleure configuration :",
    best_configuration[
        "configuration"
    ]
)

print(
    "Evidence Recall@1 :",
    round(
        best_configuration[
            "evidence_recall_at_1"
        ],
        4
    )
)

print(
    "Evidence Recall@5 :",
    round(
        best_configuration[
            "evidence_recall_at_5"
        ],
        4
    )
)

print(
    "Evidence MRR :",
    round(
        best_configuration[
            "evidence_mrr"
        ],
        4
    )
)

print(
    "Nombre de chunks :",
    int(
        best_configuration[
            "number_of_chunks"
        ]
    )
)

print(
    "Temps d'embedding :",
    round(
        best_configuration[
            "embedding_time_seconds"
        ],
        3
    ),
    "secondes"
)

Meilleure configuration : fixed_1024
Evidence Recall@1 : 0.5667
Evidence Recall@5 : 1.0
Evidence MRR : 0.7378
Nombre de chunks : 1478
Temps d'embedding : 656.038 secondes